// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shentu/gov/v1alpha1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/x/gov/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("shentu/gov/v1alpha1/tx.proto", fileDescriptor_f5034648f58c6e59) }

var fileDescriptor_f5034648f58c6e59 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x1b, 0x40, 0x20, 0x65, 0x60, 0x30, 0x2c, 0xb8, 0xc8, 0x0b, 0x82, 0x0d, 0x5b, 0x81,
	0x37, 0x40, 0x0c, 0x0c, 0x54, 0xe2, 0x47, 0x62, 0x60, 0x41, 0x76, 0x71, 0x9c, 0x48, 0x89, 0xaf,
	0xd5, 0xeb, 0x44, 0xed, 0x2b, 0x30, 0xf1, 0x58, 0x8c, 0x1d, 0x3b, 0xa2, 0xe4, 0x45, 0x50, 0xe3,
	0x04, 0x89, 0xa1, 0x15, 0x9b, 0xcf, 0xfd, 0xce, 0x39, 0xba, 0xf2, 0x8d, 0x4f, 0x31, 0xd3, 0xd6,
	0x57, 0xc2, 0x40, 0x2d, 0xea, 0x44, 0x16, 0x2e, 0x93, 0x89, 0xf0, 0x73, 0xee, 0x66, 0xe0, 0x81,
	0x1c, 0x05, 0xca, 0x0d, 0xd4, 0x7c, 0xa0, 0x94, 0x4d, 0x01, 0x4b, 0x40, 0xa1, 0x24, 0x6a, 0x51,
	0x27, 0x4a, 0x7b, 0x99, 0x88, 0x29, 0xe4, 0x36, 0x84, 0xe8, 0xb8, 0xe7, 0xa1, 0x32, 0xe0, 0xa1,
	0x91, 0x9e, 0x04, 0xf8, 0xd6, 0x29, 0x11, 0x44, 0x8f, 0x8e, 0x0d, 0x18, 0x08, 0xf3, 0xf5, 0x6b,
	0x08, 0x18, 0x00, 0x53, 0x68, 0xd1, 0x29, 0x55, 0xa5, 0x42, 0xda, 0x45, 0x40, 0x57, 0x1f, 0x3b,
	0xf1, 0xee, 0x04, 0x0d, 0x49, 0xe3, 0xc3, 0xe7, 0x4a, 0x95, 0xb9, 0x7f, 0x98, 0x81, 0x03, 0x94,
	0x05, 0x39, 0xe7, 0x7d, 0x73, 0x58, 0xbc, 0xdb, 0x81, 0x4f, 0xd0, 0xfc, 0xb5, 0xd1, 0xcb, 0x7f,
	0xd9, 0x9e, 0x34, 0x3a, 0xb0, 0xa8, 0xc9, 0x5d, 0xbc, 0xf7, 0x02, 0x5e, 0x93, 0xf1, 0x86, 0xd8,
	0x1a, 0xd2, 0xb3, 0x2d, 0xf0, 0xb7, 0xe9, 0x31, 0x3e, 0xb8, 0xd5, 0x0e, 0x30, 0xf7, 0x84, 0x6d,
	0xf0, 0xf7, 0x9c, 0x5e, 0x6c, 0xe7, 0x43, 0xe5, 0xcd, 0xfd, 0x57, 0xc3, 0xa2, 0x65, 0xc3, 0xa2,
	0x55, 0xc3, 0xa2, 0xef, 0x86, 0x45, 0x9f, 0x2d, 0x1b, 0x2d, 0x5b, 0x36, 0x5a, 0xb5, 0x6c, 0xf4,
	0xca, 0x4d, 0xee, 0xb3, 0x4a, 0xf1, 0x29, 0x94, 0x22, 0xdc, 0x34, 0x85, 0xca, 0xbe, 0x4b, 0x9f,
	0x83, 0xed, 0x07, 0x62, 0xde, 0x5d, 0xcc, 0x2f, 0x9c, 0x46, 0xb5, 0xdf, 0xfd, 0xf0, 0xf5, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0xad, 0x10, 0x3d, 0x1f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitProposal defines a method to create new proposal given a content.
	SubmitProposal(ctx context.Context, in *types.MsgSubmitProposal, opts ...grpc.CallOption) (*types.MsgSubmitProposalResponse, error)
	// Vote defines a method to add a vote on a specific proposal.
	Vote(ctx context.Context, in *types.MsgVote, opts ...grpc.CallOption) (*types.MsgVoteResponse, error)
	// Deposit defines a method to add deposit on a specific proposal.
	Deposit(ctx context.Context, in *types.MsgDeposit, opts ...grpc.CallOption) (*types.MsgDepositResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitProposal(ctx context.Context, in *types.MsgSubmitProposal, opts ...grpc.CallOption) (*types.MsgSubmitProposalResponse, error) {
	out := new(types.MsgSubmitProposalResponse)
	err := c.cc.Invoke(ctx, "/shentu.gov.v1alpha1.Msg/SubmitProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Vote(ctx context.Context, in *types.MsgVote, opts ...grpc.CallOption) (*types.MsgVoteResponse, error) {
	out := new(types.MsgVoteResponse)
	err := c.cc.Invoke(ctx, "/shentu.gov.v1alpha1.Msg/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Deposit(ctx context.Context, in *types.MsgDeposit, opts ...grpc.CallOption) (*types.MsgDepositResponse, error) {
	out := new(types.MsgDepositResponse)
	err := c.cc.Invoke(ctx, "/shentu.gov.v1alpha1.Msg/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitProposal defines a method to create new proposal given a content.
	SubmitProposal(context.Context, *types.MsgSubmitProposal) (*types.MsgSubmitProposalResponse, error)
	// Vote defines a method to add a vote on a specific proposal.
	Vote(context.Context, *types.MsgVote) (*types.MsgVoteResponse, error)
	// Deposit defines a method to add deposit on a specific proposal.
	Deposit(context.Context, *types.MsgDeposit) (*types.MsgDepositResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitProposal(ctx context.Context, req *types.MsgSubmitProposal) (*types.MsgSubmitProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProposal not implemented")
}
func (*UnimplementedMsgServer) Vote(ctx context.Context, req *types.MsgVote) (*types.MsgVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (*UnimplementedMsgServer) Deposit(ctx context.Context, req *types.MsgDeposit) (*types.MsgDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgSubmitProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.gov.v1alpha1.Msg/SubmitProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitProposal(ctx, req.(*types.MsgSubmitProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.gov.v1alpha1.Msg/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Vote(ctx, req.(*types.MsgVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.gov.v1alpha1.Msg/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Deposit(ctx, req.(*types.MsgDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shentu.gov.v1alpha1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProposal",
			Handler:    _Msg_SubmitProposal_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Msg_Vote_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _Msg_Deposit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shentu/gov/v1alpha1/tx.proto",
}
