// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shentu/nft/v1alpha1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/irisnet/irismod/modules/nft/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateNFTAdmin struct {
	Issuer  string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgCreateNFTAdmin) Reset()         { *m = MsgCreateNFTAdmin{} }
func (m *MsgCreateNFTAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgCreateNFTAdmin) ProtoMessage()    {}
func (*MsgCreateNFTAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb0e86de90ef9e6, []int{0}
}
func (m *MsgCreateNFTAdmin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateNFTAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MsgCreateNFTAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateNFTAdmin.Merge(m, src)
}
func (m *MsgCreateNFTAdmin) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateNFTAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateNFTAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateNFTAdmin proto.InternalMessageInfo

func (m *MsgCreateNFTAdmin) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *MsgCreateNFTAdmin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgIssueNFTAdminResponse struct {
}

func (m *MsgIssueNFTAdminResponse) Reset()         { *m = MsgIssueNFTAdminResponse{} }
func (m *MsgIssueNFTAdminResponse) String() string { return proto.CompactTextString(m) }
func (*MsgIssueNFTAdminResponse) ProtoMessage()    {}
func (*MsgIssueNFTAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb0e86de90ef9e6, []int{1}
}
func (m *MsgIssueNFTAdminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueNFTAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MsgIssueNFTAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueNFTAdminResponse.Merge(m, src)
}
func (m *MsgIssueNFTAdminResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueNFTAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueNFTAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueNFTAdminResponse proto.InternalMessageInfo

type MsgRevokeNFTAdmin struct {
	Revoker string `protobuf:"bytes,1,opt,name=revoker,proto3" json:"revoker,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgRevokeNFTAdmin) Reset()         { *m = MsgRevokeNFTAdmin{} }
func (m *MsgRevokeNFTAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeNFTAdmin) ProtoMessage()    {}
func (*MsgRevokeNFTAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb0e86de90ef9e6, []int{2}
}
func (m *MsgRevokeNFTAdmin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeNFTAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MsgRevokeNFTAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeNFTAdmin.Merge(m, src)
}
func (m *MsgRevokeNFTAdmin) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeNFTAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeNFTAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeNFTAdmin proto.InternalMessageInfo

func (m *MsgRevokeNFTAdmin) GetRevoker() string {
	if m != nil {
		return m.Revoker
	}
	return ""
}

func (m *MsgRevokeNFTAdmin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgRevokeAdminResponse struct {
}

func (m *MsgRevokeAdminResponse) Reset()         { *m = MsgRevokeAdminResponse{} }
func (m *MsgRevokeAdminResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeAdminResponse) ProtoMessage()    {}
func (*MsgRevokeAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb0e86de90ef9e6, []int{3}
}
func (m *MsgRevokeAdminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MsgRevokeAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeAdminResponse.Merge(m, src)
}
func (m *MsgRevokeAdminResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeAdminResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateNFTAdmin)(nil), "shentu.nft.v1alpha1.MsgCreateNFTAdmin")
	proto.RegisterType((*MsgIssueNFTAdminResponse)(nil), "shentu.nft.v1alpha1.MsgIssueNFTAdminResponse")
	proto.RegisterType((*MsgRevokeNFTAdmin)(nil), "shentu.nft.v1alpha1.MsgRevokeNFTAdmin")
	proto.RegisterType((*MsgRevokeAdminResponse)(nil), "shentu.nft.v1alpha1.MsgRevokeAdminResponse")
}

func init() { proto.RegisterFile("shentu/nft/v1alpha1/tx.proto", fileDescriptor_6cb0e86de90ef9e6) }

var fileDescriptor_6cb0e86de90ef9e6 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xd1, 0xaa, 0xd3, 0x30,
	0x18, 0xc7, 0x57, 0x95, 0x33, 0x8c, 0x70, 0xc0, 0x78, 0x98, 0x25, 0x4a, 0x95, 0x0a, 0x22, 0x88,
	0x29, 0xd3, 0x27, 0x70, 0x73, 0x13, 0x61, 0x9d, 0x30, 0x76, 0xe5, 0x5d, 0xb7, 0xa6, 0x5d, 0x98,
	0x4d, 0x4a, 0x92, 0x8e, 0xf9, 0x16, 0xbe, 0x93, 0x37, 0x5e, 0xee, 0x72, 0x97, 0xd2, 0xbd, 0x88,
	0x2c, 0x4b, 0x76, 0xb6, 0xae, 0xdd, 0x5d, 0xd3, 0xdf, 0x9f, 0xdf, 0xff, 0x6b, 0xf9, 0x02, 0x5e,
	0xca, 0x05, 0x61, 0xaa, 0x08, 0x58, 0xa2, 0x82, 0x55, 0x37, 0xfa, 0x99, 0x2f, 0xa2, 0x6e, 0xa0,
	0xd6, 0x38, 0x17, 0x5c, 0x71, 0xf8, 0xec, 0x40, 0x31, 0x4b, 0x14, 0xb6, 0x14, 0xdd, 0xa5, 0x3c,
	0xe5, 0x9a, 0x07, 0xfb, 0xa7, 0x43, 0x14, 0xdd, 0x51, 0x41, 0x65, 0xc6, 0x63, 0x6d, 0xb2, 0x02,
	0x7f, 0x00, 0x9e, 0x86, 0x32, 0xed, 0x0b, 0x12, 0x29, 0x32, 0x1e, 0x4e, 0x3f, 0xc7, 0x19, 0x65,
	0xb0, 0x03, 0x6e, 0xa8, 0x94, 0x05, 0x11, 0xae, 0xf3, 0xda, 0x79, 0xf7, 0x78, 0x62, 0x4e, 0xd0,
	0x05, 0xed, 0x28, 0x8e, 0x05, 0x91, 0xd2, 0x7d, 0xa0, 0x81, 0x3d, 0xfa, 0x08, 0xb8, 0xa1, 0x4c,
	0xbf, 0xed, 0x63, 0xd6, 0x32, 0x21, 0x32, 0xe7, 0x4c, 0x12, 0xff, 0xab, 0xae, 0x98, 0x90, 0x15,
	0x5f, 0xde, 0x57, 0xb8, 0xa0, 0x2d, 0xf4, 0x1b, 0xdb, 0x61, 0x8f, 0x57, 0x4a, 0x5c, 0xd0, 0x39,
	0x8a, 0xce, 0x2a, 0x3e, 0xfe, 0x79, 0x04, 0x1e, 0x86, 0x32, 0x85, 0x23, 0x00, 0xf4, 0x0c, 0x5f,
	0x08, 0xe3, 0x19, 0x44, 0xd8, 0x7c, 0xb2, 0xfe, 0x3d, 0x76, 0x3e, 0xcd, 0x90, 0xdf, 0xcc, 0xac,
	0x15, 0xf6, 0x41, 0x3b, 0xa4, 0x4c, 0x8d, 0x87, 0x53, 0xf8, 0xbc, 0x1a, 0x37, 0x00, 0xbd, 0x6a,
	0x00, 0xa7, 0x92, 0x41, 0x4c, 0xeb, 0x25, 0x06, 0x5c, 0x4a, 0x0c, 0x38, 0x4a, 0xbe, 0x83, 0x27,
	0x53, 0x11, 0x31, 0x99, 0x10, 0xb1, 0x17, 0xbd, 0xa8, 0xe6, 0x4f, 0x20, 0x7a, 0x73, 0x05, 0x9e,
	0x4e, 0xd5, 0x2b, 0x04, 0xab, 0x9d, 0xca, 0x80, 0xcb, 0xa9, 0x0c, 0x38, 0x4a, 0x52, 0x70, 0x5b,
	0x59, 0x9c, 0xb7, 0xb8, 0x66, 0x1f, 0xf1, 0xc5, 0x82, 0xa1, 0x0f, 0x4d, 0xb9, 0xda, 0x0d, 0x82,
	0x04, 0xdc, 0x56, 0xd6, 0xa7, 0xb1, 0xe8, 0x3c, 0x87, 0xde, 0x5f, 0xcf, 0x9d, 0xd5, 0xf4, 0x46,
	0x7f, 0x4b, 0xcf, 0xd9, 0x94, 0x9e, 0xb3, 0x2d, 0x3d, 0xe7, 0x5f, 0xe9, 0x39, 0xbf, 0x77, 0x5e,
	0x6b, 0xb3, 0xf3, 0x5a, 0xdb, 0x9d, 0xd7, 0xfa, 0x81, 0x53, 0xaa, 0x16, 0xc5, 0x0c, 0xcf, 0x79,
	0x16, 0xcc, 0x89, 0x50, 0x74, 0x99, 0xf0, 0x82, 0xc5, 0x91, 0xa2, 0x9c, 0x05, 0xe6, 0x92, 0xae,
	0x0f, 0x97, 0xeb, 0x57, 0x4e, 0xe4, 0xec, 0x46, 0x5f, 0xb0, 0x4f, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0xaa, 0xa9, 0xb0, 0xc1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// IssueDenom defines a method for issue a denom.
	IssueDenom(ctx context.Context, in *types.MsgIssueDenom, opts ...grpc.CallOption) (*types.MsgIssueDenomResponse, error)
	// MintNFT defines a method for mint a new nft
	MintNFT(ctx context.Context, in *types.MsgMintNFT, opts ...grpc.CallOption) (*types.MsgMintNFTResponse, error)
	// RefundHTLC defines a method for editing a nft.
	EditNFT(ctx context.Context, in *types.MsgEditNFT, opts ...grpc.CallOption) (*types.MsgEditNFTResponse, error)
	// TransferNFT defines a method for transferring a nft.
	TransferNFT(ctx context.Context, in *types.MsgTransferNFT, opts ...grpc.CallOption) (*types.MsgTransferNFTResponse, error)
	// BurnNFT defines a method for burning a nft.
	BurnNFT(ctx context.Context, in *types.MsgBurnNFT, opts ...grpc.CallOption) (*types.MsgBurnNFTResponse, error)
	// CreateNFTAdmin defines a method for creating an nft admin.
	CreateNFTAdmin(ctx context.Context, in *MsgCreateNFTAdmin, opts ...grpc.CallOption) (*MsgIssueNFTAdminResponse, error)
	// RevokeNFTAdmin defines a method for revoking an nft admin.
	RevokeNFTAdmin(ctx context.Context, in *MsgRevokeNFTAdmin, opts ...grpc.CallOption) (*MsgRevokeAdminResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) IssueDenom(ctx context.Context, in *types.MsgIssueDenom, opts ...grpc.CallOption) (*types.MsgIssueDenomResponse, error) {
	out := new(types.MsgIssueDenomResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/IssueDenom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintNFT(ctx context.Context, in *types.MsgMintNFT, opts ...grpc.CallOption) (*types.MsgMintNFTResponse, error) {
	out := new(types.MsgMintNFTResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/MintNFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EditNFT(ctx context.Context, in *types.MsgEditNFT, opts ...grpc.CallOption) (*types.MsgEditNFTResponse, error) {
	out := new(types.MsgEditNFTResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/EditNFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferNFT(ctx context.Context, in *types.MsgTransferNFT, opts ...grpc.CallOption) (*types.MsgTransferNFTResponse, error) {
	out := new(types.MsgTransferNFTResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/TransferNFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnNFT(ctx context.Context, in *types.MsgBurnNFT, opts ...grpc.CallOption) (*types.MsgBurnNFTResponse, error) {
	out := new(types.MsgBurnNFTResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/BurnNFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateNFTAdmin(ctx context.Context, in *MsgCreateNFTAdmin, opts ...grpc.CallOption) (*MsgIssueNFTAdminResponse, error) {
	out := new(MsgIssueNFTAdminResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/CreateNFTAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeNFTAdmin(ctx context.Context, in *MsgRevokeNFTAdmin, opts ...grpc.CallOption) (*MsgRevokeAdminResponse, error) {
	out := new(MsgRevokeAdminResponse)
	err := c.cc.Invoke(ctx, "/shentu.nft.v1alpha1.Msg/RevokeNFTAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// IssueDenom defines a method for issue a denom.
	IssueDenom(context.Context, *types.MsgIssueDenom) (*types.MsgIssueDenomResponse, error)
	// MintNFT defines a method for mint a new nft
	MintNFT(context.Context, *types.MsgMintNFT) (*types.MsgMintNFTResponse, error)
	// RefundHTLC defines a method for editing a nft.
	EditNFT(context.Context, *types.MsgEditNFT) (*types.MsgEditNFTResponse, error)
	// TransferNFT defines a method for transferring a nft.
	TransferNFT(context.Context, *types.MsgTransferNFT) (*types.MsgTransferNFTResponse, error)
	// BurnNFT defines a method for burning a nft.
	BurnNFT(context.Context, *types.MsgBurnNFT) (*types.MsgBurnNFTResponse, error)
	// CreateNFTAdmin defines a method for creating an nft admin.
	CreateNFTAdmin(context.Context, *MsgCreateNFTAdmin) (*MsgIssueNFTAdminResponse, error)
	// RevokeNFTAdmin defines a method for revoking an nft admin.
	RevokeNFTAdmin(context.Context, *MsgRevokeNFTAdmin) (*MsgRevokeAdminResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) IssueDenom(ctx context.Context, req *types.MsgIssueDenom) (*types.MsgIssueDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueDenom not implemented")
}
func (*UnimplementedMsgServer) MintNFT(ctx context.Context, req *types.MsgMintNFT) (*types.MsgMintNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintNFT not implemented")
}
func (*UnimplementedMsgServer) EditNFT(ctx context.Context, req *types.MsgEditNFT) (*types.MsgEditNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditNFT not implemented")
}
func (*UnimplementedMsgServer) TransferNFT(ctx context.Context, req *types.MsgTransferNFT) (*types.MsgTransferNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferNFT not implemented")
}
func (*UnimplementedMsgServer) BurnNFT(ctx context.Context, req *types.MsgBurnNFT) (*types.MsgBurnNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnNFT not implemented")
}
func (*UnimplementedMsgServer) CreateNFTAdmin(ctx context.Context, req *MsgCreateNFTAdmin) (*MsgIssueNFTAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNFTAdmin not implemented")
}
func (*UnimplementedMsgServer) RevokeNFTAdmin(ctx context.Context, req *MsgRevokeNFTAdmin) (*MsgRevokeAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeNFTAdmin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_IssueDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgIssueDenom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/IssueDenom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueDenom(ctx, req.(*types.MsgIssueDenom))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgMintNFT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/MintNFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintNFT(ctx, req.(*types.MsgMintNFT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EditNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgEditNFT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EditNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/EditNFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EditNFT(ctx, req.(*types.MsgEditNFT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgTransferNFT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/TransferNFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferNFT(ctx, req.(*types.MsgTransferNFT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgBurnNFT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/BurnNFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnNFT(ctx, req.(*types.MsgBurnNFT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateNFTAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateNFTAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateNFTAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/CreateNFTAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateNFTAdmin(ctx, req.(*MsgCreateNFTAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeNFTAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeNFTAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeNFTAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.nft.v1alpha1.Msg/RevokeNFTAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeNFTAdmin(ctx, req.(*MsgRevokeNFTAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shentu.nft.v1alpha1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueDenom",
			Handler:    _Msg_IssueDenom_Handler,
		},
		{
			MethodName: "MintNFT",
			Handler:    _Msg_MintNFT_Handler,
		},
		{
			MethodName: "EditNFT",
			Handler:    _Msg_EditNFT_Handler,
		},
		{
			MethodName: "TransferNFT",
			Handler:    _Msg_TransferNFT_Handler,
		},
		{
			MethodName: "BurnNFT",
			Handler:    _Msg_BurnNFT_Handler,
		},
		{
			MethodName: "CreateNFTAdmin",
			Handler:    _Msg_CreateNFTAdmin_Handler,
		},
		{
			MethodName: "RevokeNFTAdmin",
			Handler:    _Msg_RevokeNFTAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shentu/nft/v1alpha1/tx.proto",
}

func (m *MsgCreateNFTAdmin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateNFTAdmin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateNFTAdmin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIssueNFTAdminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueNFTAdminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueNFTAdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRevokeNFTAdmin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeNFTAdmin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeNFTAdmin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Revoker) > 0 {
		i -= len(m.Revoker)
		copy(dAtA[i:], m.Revoker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Revoker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeAdminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeAdminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeAdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateNFTAdmin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgIssueNFTAdminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRevokeNFTAdmin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Revoker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevokeAdminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateNFTAdmin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateNFTAdmin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateNFTAdmin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueNFTAdminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueNFTAdminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueNFTAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeNFTAdmin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeNFTAdmin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeNFTAdmin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Revoker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeAdminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeAdminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
