run:
  tests: false
  skip-dirs:
    - tests/e2e
    # TODO: include below
    - x/gov
  timeout: 5m

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - exportloopref
    #- gci
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    #- revive
    - staticcheck
    - stylecheck
    - typecheck
    - thelper
    - unconvert
    - unparam
    - unused  

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - golint
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - text: "put a space between `//` and comment text"
      linters:
        - gocritic
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - text: "SA1019: codec.LegacyAmino is deprecated"
      linters:
        - staticcheck
    - text: "don't use underscores in Go names"
      linters:
        - golint
    - text: "should not use dot imports"
      linters:
        - golint
    - text: "ST1001: should not use dot imports"
      linters:
        - stylecheck
    - text: "ifElseChain: rewrite if-else to switch statement"
      linters:
        - gocritic
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
