// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shentu/bank/v1alpha1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgLockedSend represents a message to send and lock coins from one account to
// another.
type MsgLockedSend struct {
	FromAddress     string                                   `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty" yaml:"from_address"`
	ToAddress       string                                   `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty" yaml:"to_address"`
	UnlockerAddress string                                   `protobuf:"bytes,3,opt,name=unlocker_address,json=unlockerAddress,proto3" json:"unlocker_address,omitempty" yaml:"unlocker_address"`
	Amount          github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgLockedSend) Reset()         { *m = MsgLockedSend{} }
func (m *MsgLockedSend) String() string { return proto.CompactTextString(m) }
func (*MsgLockedSend) ProtoMessage()    {}
func (*MsgLockedSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e48e53fa83c4dd7, []int{0}
}
func (m *MsgLockedSend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockedSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockedSend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockedSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockedSend.Merge(m, src)
}
func (m *MsgLockedSend) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockedSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockedSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockedSend proto.InternalMessageInfo

// MsgLockedSendResponse defines the Msg/LockedSend response type.
type MsgLockedSendResponse struct {
}

func (m *MsgLockedSendResponse) Reset()         { *m = MsgLockedSendResponse{} }
func (m *MsgLockedSendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLockedSendResponse) ProtoMessage()    {}
func (*MsgLockedSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e48e53fa83c4dd7, []int{1}
}
func (m *MsgLockedSendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockedSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockedSendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockedSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockedSendResponse.Merge(m, src)
}
func (m *MsgLockedSendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockedSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockedSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockedSendResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLockedSend)(nil), "shentu.bank.v1alpha1.MsgLockedSend")
	proto.RegisterType((*MsgLockedSendResponse)(nil), "shentu.bank.v1alpha1.MsgLockedSendResponse")
}

func init() { proto.RegisterFile("shentu/bank/v1alpha1/tx.proto", fileDescriptor_9e48e53fa83c4dd7) }

var fileDescriptor_9e48e53fa83c4dd7 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xed, 0x06, 0x2a, 0xf5, 0x0a, 0x82, 0x9a, 0x56, 0x29, 0x41, 0xd8, 0x95, 0x59, 0xa2,
	0x20, 0xee, 0xea, 0xc2, 0x94, 0x8d, 0x20, 0x21, 0x21, 0xd1, 0xc5, 0x6c, 0x0c, 0xa0, 0xb3, 0x7d,
	0x75, 0xac, 0xc4, 0xf7, 0x22, 0xdf, 0x39, 0x6a, 0x37, 0xc4, 0x84, 0x98, 0xf8, 0x08, 0x9d, 0x99,
	0xf2, 0x31, 0x3a, 0x76, 0x64, 0x32, 0x55, 0x32, 0x84, 0x39, 0x9f, 0x00, 0xf9, 0xce, 0x2e, 0x31,
	0x30, 0x74, 0xf1, 0xf9, 0xde, 0xef, 0xfd, 0xff, 0xcf, 0xfa, 0xfb, 0xa1, 0xc7, 0x62, 0xc8, 0xb8,
	0xcc, 0x49, 0x40, 0xf9, 0x88, 0x4c, 0x3d, 0x3a, 0x9e, 0x0c, 0xa9, 0x47, 0xe4, 0x29, 0x9e, 0x64,
	0x20, 0xc1, 0xda, 0xd5, 0x18, 0x97, 0x18, 0xd7, 0xb8, 0xb3, 0x1b, 0x43, 0x0c, 0xaa, 0x81, 0x94,
	0x6f, 0xba, 0xb7, 0x63, 0x87, 0x20, 0x52, 0x10, 0x24, 0xa0, 0x82, 0x91, 0xa9, 0x17, 0x30, 0x49,
	0x3d, 0x12, 0x42, 0xc2, 0xff, 0xe1, 0x6a, 0x94, 0xe6, 0xca, 0x58, 0xf3, 0x76, 0xc5, 0x53, 0x11,
	0x93, 0xa9, 0x57, 0x1e, 0x15, 0xd8, 0xa1, 0x69, 0xc2, 0x81, 0xa8, 0xa7, 0x2e, 0xb9, 0x57, 0x1b,
	0xe8, 0xee, 0xb1, 0x88, 0xdf, 0x42, 0x38, 0x62, 0xd1, 0x3b, 0xc6, 0x23, 0xab, 0x8f, 0xee, 0x9c,
	0x64, 0x90, 0x7e, 0xa4, 0x51, 0x94, 0x31, 0x21, 0xf6, 0xcd, 0x03, 0xb3, 0xbb, 0x35, 0x68, 0xaf,
	0x0a, 0xe7, 0xc1, 0x19, 0x4d, 0xc7, 0x7d, 0x77, 0x9d, 0xba, 0xfe, 0x76, 0x79, 0x7d, 0xa9, 0x6f,
	0xd6, 0x0b, 0x84, 0x24, 0x5c, 0x2b, 0x37, 0x94, 0x72, 0x6f, 0x55, 0x38, 0x3b, 0x5a, 0xf9, 0x87,
	0xb9, 0xfe, 0x96, 0x84, 0x5a, 0xf5, 0x1a, 0xdd, 0xcf, 0xf9, 0xb8, 0xfc, 0x82, 0xec, 0x5a, 0xdb,
	0x52, 0xda, 0x47, 0xab, 0xc2, 0x69, 0x6b, 0xed, 0xdf, 0x1d, 0xae, 0x7f, 0xaf, 0x2e, 0xd5, 0x3e,
	0x21, 0xda, 0xa4, 0x29, 0xe4, 0x5c, 0xee, 0xdf, 0x3a, 0x68, 0x75, 0xb7, 0x8f, 0x1e, 0x62, 0x1d,
	0x04, 0x2e, 0x83, 0xc4, 0x55, 0x50, 0xf8, 0x15, 0x24, 0x7c, 0x70, 0x78, 0x51, 0x38, 0xc6, 0xf7,
	0x9f, 0x4e, 0x37, 0x4e, 0xe4, 0x30, 0x0f, 0x70, 0x08, 0x29, 0xa9, 0x52, 0xd3, 0xc7, 0x33, 0x11,
	0x8d, 0x88, 0x3c, 0x9b, 0x30, 0xa1, 0x04, 0xc2, 0xaf, 0xac, 0xfb, 0x87, 0x5f, 0xce, 0x1d, 0xe3,
	0xd7, 0xb9, 0x63, 0x7c, 0x5e, 0xce, 0x7a, 0x8d, 0xa4, 0xbe, 0x2e, 0x67, 0x3d, 0x4b, 0xfd, 0x93,
	0x46, 0xa0, 0x6e, 0x1b, 0xed, 0x35, 0x0a, 0x3e, 0x13, 0x13, 0xe0, 0x82, 0x1d, 0x8d, 0x51, 0xeb,
	0x58, 0xc4, 0xd6, 0x07, 0x84, 0xd6, 0xe2, 0x7f, 0x82, 0xff, 0xb7, 0x29, 0xb8, 0xe1, 0xd0, 0x79,
	0x7a, 0x83, 0xa6, 0x7a, 0x4c, 0xe7, 0xf6, 0xa7, 0xe5, 0xac, 0x67, 0x0e, 0xde, 0x5c, 0xcc, 0x6d,
	0xf3, 0x72, 0x6e, 0x9b, 0x57, 0x73, 0xdb, 0xfc, 0xb6, 0xb0, 0x8d, 0xcb, 0x85, 0x6d, 0xfc, 0x58,
	0xd8, 0xc6, 0x7b, 0xb2, 0x16, 0x82, 0xf6, 0x3d, 0x81, 0x9c, 0x47, 0x54, 0x26, 0xc0, 0xab, 0x02,
	0x39, 0xd5, 0xdb, 0xa6, 0x12, 0x09, 0x36, 0xd5, 0xee, 0x3c, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x14, 0x5b, 0x34, 0xf4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// LockedSend defines a method for sending coins and locking them from one
	// account to another account.
	LockedSend(ctx context.Context, in *MsgLockedSend, opts ...grpc.CallOption) (*MsgLockedSendResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LockedSend(ctx context.Context, in *MsgLockedSend, opts ...grpc.CallOption) (*MsgLockedSendResponse, error) {
	out := new(MsgLockedSendResponse)
	err := c.cc.Invoke(ctx, "/shentu.bank.v1alpha1.Msg/LockedSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// LockedSend defines a method for sending coins and locking them from one
	// account to another account.
	LockedSend(context.Context, *MsgLockedSend) (*MsgLockedSendResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LockedSend(ctx context.Context, req *MsgLockedSend) (*MsgLockedSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockedSend not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LockedSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLockedSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LockedSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shentu.bank.v1alpha1.Msg/LockedSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LockedSend(ctx, req.(*MsgLockedSend))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shentu.bank.v1alpha1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockedSend",
			Handler:    _Msg_LockedSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shentu/bank/v1alpha1/tx.proto",
}

func (m *MsgLockedSend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockedSend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockedSend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.UnlockerAddress) > 0 {
		i -= len(m.UnlockerAddress)
		copy(dAtA[i:], m.UnlockerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UnlockerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLockedSendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockedSendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockedSendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLockedSend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UnlockerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgLockedSendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLockedSend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockedSend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockedSend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockedSendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockedSendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockedSendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
