// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shentu/cert/v1alpha1/cert.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CertificateType int32

const (
	CertificateTypeNil               CertificateType = 0
	CertificateTypeCompilation       CertificateType = 1
	CertificateTypeAuditing          CertificateType = 2
	CertificateTypeProof             CertificateType = 3
	CertificateTypeOracleOperator    CertificateType = 4
	CertificateTypeShieldPoolCreator CertificateType = 5
	CertificateTypeIdentity          CertificateType = 6
	CertificateTypeGeneral           CertificateType = 7
)

var CertificateType_name = map[int32]string{
	0: "CERT_TYPE_UNSPECIFIED",
	1: "CERT_TYPE_COMPILATION",
	2: "CERT_TYPE_AUDITING",
	3: "CERT_TYPE_PROOF",
	4: "CERT_TYPE_ORACLE_OPERATOR",
	5: "CERT_TYPE_SHIELD_POOL_CREATOR",
	6: "CERT_TYPE_IDENTITY",
	7: "CERT_TYPE_GENERAL",
}

var CertificateType_value = map[string]int32{
	"CERT_TYPE_UNSPECIFIED":         0,
	"CERT_TYPE_COMPILATION":         1,
	"CERT_TYPE_AUDITING":            2,
	"CERT_TYPE_PROOF":               3,
	"CERT_TYPE_ORACLE_OPERATOR":     4,
	"CERT_TYPE_SHIELD_POOL_CREATOR": 5,
	"CERT_TYPE_IDENTITY":            6,
	"CERT_TYPE_GENERAL":             7,
}

func (x CertificateType) String() string {
	return proto.EnumName(CertificateType_name, int32(x))
}

func (CertificateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{0}
}

type RequestContentType int32

const (
	RequestContentTypeNil            RequestContentType = 0
	RequestContentTypeSourceCodeHash RequestContentType = 1
	RequestContentTypeAddress        RequestContentType = 2
	RequestContentTypeBytecodeHash   RequestContentType = 3
	RequestContentTypeGeneral        RequestContentType = 4
)

var RequestContentType_name = map[int32]string{
	0: "REQ_CONTENT_TYPE_UNSPECIFIED",
	1: "REQ_CONTENT_TYPE_SOURCE_CODE_HASH",
	2: "REQ_CONTENT_TYPE_ADDRESS",
	3: "REQ_CONTENT_TYPE_BYTECODE_HASH",
	4: "REQ_CONTENT_TYPE_GENERAL",
}

var RequestContentType_value = map[string]int32{
	"REQ_CONTENT_TYPE_UNSPECIFIED":      0,
	"REQ_CONTENT_TYPE_SOURCE_CODE_HASH": 1,
	"REQ_CONTENT_TYPE_ADDRESS":          2,
	"REQ_CONTENT_TYPE_BYTECODE_HASH":    3,
	"REQ_CONTENT_TYPE_GENERAL":          4,
}

func (RequestContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{1}
}

type Certifier struct {
	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	Alias       string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty" yaml:"alias"`
	Proposer    string `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty" yaml:"proposer"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" yaml:"description"`
}

func (m *Certifier) Reset()         { *m = Certifier{} }
func (m *Certifier) String() string { return proto.CompactTextString(m) }
func (*Certifier) ProtoMessage()    {}
func (*Certifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{0}
}
func (m *Certifier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Certifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Certifier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Certifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certifier.Merge(m, src)
}
func (m *Certifier) XXX_Size() int {
	return m.Size()
}
func (m *Certifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Certifier.DiscardUnknown(m)
}

var xxx_messageInfo_Certifier proto.InternalMessageInfo

type RequestContent struct {
	RequestContentType RequestContentType `protobuf:"varint,1,opt,name=request_content_type,json=requestContentType,proto3,enum=shentu.cert.v1alpha1.RequestContentType" json:"request_content_type,omitempty" yaml:"request_content_type"`
	RequestContent     string             `protobuf:"bytes,2,opt,name=request_content,json=requestContent,proto3" json:"request_content,omitempty" yaml:"request_content"`
}

func (m *RequestContent) Reset()         { *m = RequestContent{} }
func (m *RequestContent) String() string { return proto.CompactTextString(m) }
func (*RequestContent) ProtoMessage()    {}
func (*RequestContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{1}
}
func (m *RequestContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestContent.Merge(m, src)
}
func (m *RequestContent) XXX_Size() int {
	return m.Size()
}
func (m *RequestContent) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestContent.DiscardUnknown(m)
}

var xxx_messageInfo_RequestContent proto.InternalMessageInfo

type GeneralCertificate struct {
	CertId          CertificateID   `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3,casttype=CertificateID" json:"cert_id,omitempty" yaml:"certificate_id"`
	CertType        CertificateType `protobuf:"varint,2,opt,name=cert_type,json=certType,proto3,enum=shentu.cert.v1alpha1.CertificateType" json:"cert_type,omitempty" yaml:"certificate_type"`
	ReqContent      *RequestContent `protobuf:"bytes,3,opt,name=req_content,json=reqContent,proto3" json:"req_content,omitempty" yaml:"request_content"`
	CertDescription string          `protobuf:"bytes,4,opt,name=cert_description,json=certDescription,proto3" json:"cert_description,omitempty" yaml:"description"`
	CertCertifier   string          `protobuf:"bytes,5,opt,name=cert_certifier,json=certCertifier,proto3" json:"cert_certifier,omitempty" yaml:"certifier"`
	CertTxHash      string          `protobuf:"bytes,6,opt,name=cert_tx_hash,json=certTxHash,proto3" json:"cert_tx_hash,omitempty" yaml:"txhash"`
}

func (m *GeneralCertificate) Reset()         { *m = GeneralCertificate{} }
func (m *GeneralCertificate) String() string { return proto.CompactTextString(m) }
func (*GeneralCertificate) ProtoMessage()    {}
func (*GeneralCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{2}
}
func (m *GeneralCertificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GeneralCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GeneralCertificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GeneralCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralCertificate.Merge(m, src)
}
func (m *GeneralCertificate) XXX_Size() int {
	return m.Size()
}
func (m *GeneralCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralCertificate proto.InternalMessageInfo

type CompilationCertificateContent struct {
	Compiler     string `protobuf:"bytes,1,opt,name=compiler,proto3" json:"compiler,omitempty" yaml:"compiler"`
	BytecodeHash string `protobuf:"bytes,2,opt,name=bytecode_hash,json=bytecodeHash,proto3" json:"bytecode_hash,omitempty" yaml:"bytecode_hash"`
}

func (m *CompilationCertificateContent) Reset()         { *m = CompilationCertificateContent{} }
func (m *CompilationCertificateContent) String() string { return proto.CompactTextString(m) }
func (*CompilationCertificateContent) ProtoMessage()    {}
func (*CompilationCertificateContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{3}
}
func (m *CompilationCertificateContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompilationCertificateContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompilationCertificateContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompilationCertificateContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompilationCertificateContent.Merge(m, src)
}
func (m *CompilationCertificateContent) XXX_Size() int {
	return m.Size()
}
func (m *CompilationCertificateContent) XXX_DiscardUnknown() {
	xxx_messageInfo_CompilationCertificateContent.DiscardUnknown(m)
}

var xxx_messageInfo_CompilationCertificateContent proto.InternalMessageInfo

type CompilationCertificate struct {
	IssueBlockHeight int64                          `protobuf:"varint,1,opt,name=issue_block_height,json=issueBlockHeight,proto3" json:"issue_block_height,omitempty" yaml:"time_issued"`
	CertId           CertificateID                  `protobuf:"bytes,2,opt,name=cert_id,json=certId,proto3,casttype=CertificateID" json:"cert_id,omitempty" yaml:"certificate_id"`
	CertType         CertificateType                `protobuf:"varint,3,opt,name=cert_type,json=certType,proto3,enum=shentu.cert.v1alpha1.CertificateType" json:"cert_type,omitempty" yaml:"certificate_type"`
	ReqContent       *RequestContent                `protobuf:"bytes,4,opt,name=req_content,json=reqContent,proto3" json:"req_content,omitempty" yaml:"request_content"`
	CertContent      *CompilationCertificateContent `protobuf:"bytes,5,opt,name=cert_content,json=certContent,proto3" json:"cert_content,omitempty" yaml:"certificate_content"`
	CertDescription  string                         `protobuf:"bytes,6,opt,name=cert_description,json=certDescription,proto3" json:"cert_description,omitempty" yaml:"description"`
	CertCertifier    string                         `protobuf:"bytes,7,opt,name=cert_certifier,json=certCertifier,proto3" json:"cert_certifier,omitempty" yaml:"certifier"`
	CertTxHash       string                         `protobuf:"bytes,8,opt,name=cert_tx_hash,json=certTxHash,proto3" json:"cert_tx_hash,omitempty" yaml:"txhash"`
}

func (m *CompilationCertificate) Reset()         { *m = CompilationCertificate{} }
func (m *CompilationCertificate) String() string { return proto.CompactTextString(m) }
func (*CompilationCertificate) ProtoMessage()    {}
func (*CompilationCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{4}
}
func (m *CompilationCertificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompilationCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompilationCertificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompilationCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompilationCertificate.Merge(m, src)
}
func (m *CompilationCertificate) XXX_Size() int {
	return m.Size()
}
func (m *CompilationCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_CompilationCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_CompilationCertificate proto.InternalMessageInfo

// Validator is a type for certified validator.
type Validator struct {
	Pubkey    *types.Any `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Certifier string     `protobuf:"bytes,2,opt,name=certifier,proto3" json:"certifier,omitempty"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{5}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

// Library is a type for certified libraries.
type Library struct {
	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Publisher string `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (m *Library) Reset()         { *m = Library{} }
func (m *Library) String() string { return proto.CompactTextString(m) }
func (*Library) ProtoMessage()    {}
func (*Library) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{6}
}
func (m *Library) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Library) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Library.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Library) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Library.Merge(m, src)
}
func (m *Library) XXX_Size() int {
	return m.Size()
}
func (m *Library) XXX_DiscardUnknown() {
	xxx_messageInfo_Library.DiscardUnknown(m)
}

var xxx_messageInfo_Library proto.InternalMessageInfo

// CertificateProto is a proto wrapper for Certificate interface.
type CertificateProto struct {
	Certificate *types.Any `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (m *CertificateProto) Reset()         { *m = CertificateProto{} }
func (m *CertificateProto) String() string { return proto.CompactTextString(m) }
func (*CertificateProto) ProtoMessage()    {}
func (*CertificateProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{7}
}
func (m *CertificateProto) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CertificateProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CertificateProto.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CertificateProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateProto.Merge(m, src)
}
func (m *CertificateProto) XXX_Size() int {
	return m.Size()
}
func (m *CertificateProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateProto.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateProto proto.InternalMessageInfo

// CertifierUpdateProposal adds or removes a certifier
type CertifierUpdateProposal struct {
	Title       string      `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty" yaml:"title"`
	Proposer    string      `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty" yaml:"proposer"`
	Alias       string      `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty" yaml:"alias"`
	Certifier   string      `protobuf:"bytes,4,opt,name=certifier,proto3" json:"certifier,omitempty" yaml:"certifier"`
	Description string      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" yaml:"description"`
	AddOrRemove AddOrRemove `protobuf:"varint,6,opt,name=add_or_remove,json=addOrRemove,proto3,casttype=AddOrRemove" json:"add_or_remove,omitempty" yaml:"add_or_remove"`
}

func (m *CertifierUpdateProposal) Reset()         { *m = CertifierUpdateProposal{} }
func (m *CertifierUpdateProposal) String() string { return proto.CompactTextString(m) }
func (*CertifierUpdateProposal) ProtoMessage()    {}
func (*CertifierUpdateProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{8}
}
func (m *CertifierUpdateProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CertifierUpdateProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CertifierUpdateProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CertifierUpdateProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertifierUpdateProposal.Merge(m, src)
}
func (m *CertifierUpdateProposal) XXX_Size() int {
	return m.Size()
}
func (m *CertifierUpdateProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_CertifierUpdateProposal.DiscardUnknown(m)
}

var xxx_messageInfo_CertifierUpdateProposal proto.InternalMessageInfo

type KVPair struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KVPair) Reset()         { *m = KVPair{} }
func (m *KVPair) String() string { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()    {}
func (*KVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e43b05a8c34048, []int{9}
}
func (m *KVPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVPair.Merge(m, src)
}
func (m *KVPair) XXX_Size() int {
	return m.Size()
}
func (m *KVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KVPair.DiscardUnknown(m)
}

var xxx_messageInfo_KVPair proto.InternalMessageInfo

func (m *KVPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVPair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("shentu.cert.v1alpha1.CertificateType", CertificateType_name, CertificateType_value)
	proto.RegisterEnum("shentu.cert.v1alpha1.RequestContentType", RequestContentType_name, RequestContentType_value)
	proto.RegisterType((*Certifier)(nil), "shentu.cert.v1alpha1.Certifier")
	proto.RegisterType((*RequestContent)(nil), "shentu.cert.v1alpha1.RequestContent")
	proto.RegisterType((*GeneralCertificate)(nil), "shentu.cert.v1alpha1.GeneralCertificate")
	proto.RegisterType((*CompilationCertificateContent)(nil), "shentu.cert.v1alpha1.CompilationCertificateContent")
	proto.RegisterType((*CompilationCertificate)(nil), "shentu.cert.v1alpha1.CompilationCertificate")
	proto.RegisterType((*Validator)(nil), "shentu.cert.v1alpha1.Validator")
	proto.RegisterType((*Library)(nil), "shentu.cert.v1alpha1.Library")
	proto.RegisterType((*CertificateProto)(nil), "shentu.cert.v1alpha1.CertificateProto")
	proto.RegisterType((*CertifierUpdateProposal)(nil), "shentu.cert.v1alpha1.CertifierUpdateProposal")
	proto.RegisterType((*KVPair)(nil), "shentu.cert.v1alpha1.KVPair")
}

func init() { proto.RegisterFile("shentu/cert/v1alpha1/cert.proto", fileDescriptor_14e43b05a8c34048) }

var fileDescriptor_14e43b05a8c34048 = []byte{
	// 1402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0xd6, 0xc3, 0x96, 0xe5, 0x55, 0x6c, 0x33, 0x5b, 0xc5, 0x91, 0x99, 0x58, 0x54, 0x88, 0xb4,
	0x0d, 0x82, 0x46, 0xaa, 0xed, 0x4b, 0x9b, 0xa0, 0x40, 0xf5, 0xa0, 0x6d, 0xc1, 0xae, 0xa8, 0xae,
	0xe4, 0x00, 0xe9, 0x85, 0xa0, 0xc8, 0xb5, 0x44, 0x84, 0xd6, 0x32, 0x24, 0x65, 0x58, 0xc8, 0x1f,
	0x08, 0x74, 0xea, 0xb5, 0x07, 0x15, 0x01, 0xda, 0x43, 0x7f, 0x40, 0x7e, 0x44, 0x91, 0x53, 0x4e,
	0x45, 0x0f, 0x81, 0x5a, 0x24, 0x97, 0xa2, 0x47, 0x1d, 0x7b, 0x2a, 0xb8, 0x24, 0x4d, 0xea, 0x11,
	0xc3, 0x7d, 0xe4, 0xc6, 0xdd, 0xf9, 0xbe, 0xd9, 0x9d, 0x6f, 0x66, 0x77, 0x96, 0x80, 0xb3, 0x3a,
	0xb8, 0x6b, 0xf7, 0x0a, 0x0a, 0x36, 0xed, 0xc2, 0xe9, 0x96, 0xac, 0x1b, 0x1d, 0x79, 0x8b, 0x8e,
	0xf2, 0x86, 0x49, 0x6c, 0x02, 0xd3, 0x2e, 0x20, 0x4f, 0xa7, 0x7c, 0x00, 0x9b, 0x6e, 0x93, 0x36,
	0xa1, 0x80, 0x82, 0xf3, 0xe5, 0x62, 0xd9, 0xac, 0x42, 0xac, 0x13, 0x62, 0x15, 0x5a, 0xb2, 0x85,
	0x0b, 0xa7, 0x5b, 0x2d, 0x6c, 0x3b, 0xbe, 0x88, 0xd6, 0xf5, 0xec, 0x1b, 0xae, 0x5d, 0x72, 0x89,
	0xee, 0xc0, 0x37, 0xb5, 0x09, 0x69, 0xeb, 0xb8, 0x40, 0x47, 0xad, 0xde, 0x71, 0x41, 0xee, 0xf6,
	0x5d, 0x13, 0xff, 0x4b, 0x14, 0x2c, 0x97, 0xb1, 0x69, 0x6b, 0xc7, 0x1a, 0x36, 0xe1, 0x27, 0x60,
	0x49, 0x56, 0x55, 0x13, 0x5b, 0x56, 0x26, 0x9a, 0x8b, 0xde, 0x59, 0x2e, 0xc1, 0xf1, 0x88, 0x5b,
	0xed, 0xcb, 0x27, 0xfa, 0x7d, 0xde, 0x33, 0xf0, 0xc8, 0x87, 0xc0, 0x8f, 0xc0, 0xa2, 0xac, 0x6b,
	0xb2, 0x95, 0x89, 0x51, 0x2c, 0x33, 0x1e, 0x71, 0x57, 0x3c, 0xac, 0x33, 0xcd, 0x23, 0xd7, 0x0c,
	0x0b, 0x20, 0x69, 0x98, 0xc4, 0x20, 0x16, 0x36, 0x33, 0x71, 0x0a, 0xfd, 0x60, 0x3c, 0xe2, 0xd6,
	0x5c, 0xa8, 0x6f, 0xe1, 0xd1, 0x39, 0x08, 0x7e, 0x06, 0x52, 0x2a, 0xb6, 0x14, 0x53, 0x33, 0x6c,
	0x8d, 0x74, 0x33, 0x0b, 0x94, 0xb3, 0x3e, 0x1e, 0x71, 0xd0, 0xe5, 0x84, 0x8c, 0x3c, 0x0a, 0x43,
	0xef, 0x27, 0x9f, 0x3d, 0xe7, 0x22, 0x7f, 0x3c, 0xe7, 0x22, 0xfc, 0xeb, 0x28, 0x58, 0x45, 0xf8,
	0x49, 0x0f, 0x5b, 0x76, 0x99, 0x74, 0x6d, 0xdc, 0xb5, 0xe1, 0x53, 0x90, 0x36, 0xdd, 0x19, 0x49,
	0x71, 0xa7, 0x24, 0xbb, 0x6f, 0x60, 0x1a, 0xea, 0xea, 0xf6, 0x9d, 0xfc, 0xbc, 0x64, 0xe4, 0x27,
	0x7d, 0x34, 0xfb, 0x06, 0x2e, 0x71, 0xe3, 0x11, 0x77, 0xc3, 0xdd, 0xc9, 0x3c, 0x7f, 0x3c, 0x82,
	0xe6, 0x0c, 0x09, 0x96, 0xc1, 0xda, 0x14, 0xd8, 0x93, 0x8d, 0x1d, 0x8f, 0xb8, 0xf5, 0xb9, 0xde,
	0x78, 0xb4, 0x3a, 0xe9, 0x28, 0x1c, 0x5e, 0x1c, 0xc0, 0x3d, 0xdc, 0xc5, 0xa6, 0xac, 0x7b, 0xe9,
	0x53, 0x64, 0xdb, 0x59, 0x65, 0xc9, 0xd9, 0xbe, 0xa4, 0xa9, 0x5e, 0x02, 0xef, 0x8e, 0x47, 0xdc,
	0x35, 0xd7, 0xbb, 0x12, 0xe0, 0x24, 0x4d, 0xe5, 0xff, 0x1a, 0x71, 0x2b, 0x21, 0x6a, 0xb5, 0x82,
	0x12, 0x0e, 0xa2, 0xaa, 0x42, 0x09, 0x2c, 0x53, 0x27, 0x54, 0x9c, 0x18, 0x15, 0xe7, 0xc3, 0xf9,
	0xe2, 0x84, 0xf8, 0x54, 0x99, 0x1b, 0xe3, 0x11, 0x77, 0x7d, 0x76, 0x35, 0x57, 0x95, 0xa4, 0x33,
	0x45, 0xb5, 0x90, 0x41, 0xca, 0xc4, 0x4f, 0xce, 0x75, 0x70, 0x6a, 0x22, 0xb5, 0x7d, 0xfb, 0x32,
	0xfa, 0x5f, 0xa8, 0x16, 0x30, 0xf1, 0x13, 0x3f, 0xd7, 0x45, 0xc0, 0xd0, 0x18, 0x2e, 0x5f, 0x47,
	0x6b, 0x0e, 0xbe, 0x12, 0xcc, 0xc0, 0x07, 0x60, 0x95, 0xba, 0x50, 0xfc, 0xe3, 0x91, 0x59, 0xa4,
	0x0e, 0xd2, 0xe3, 0x11, 0xc7, 0x4c, 0x04, 0xe9, 0x54, 0xef, 0x8a, 0xf3, 0x1d, 0x9c, 0xa4, 0x1d,
	0x70, 0xc5, 0xd5, 0xf0, 0x4c, 0xea, 0xc8, 0x56, 0x27, 0x93, 0xa0, 0xd4, 0xab, 0xe3, 0x11, 0xb7,
	0xe2, 0x52, 0xed, 0x33, 0x67, 0x9e, 0x47, 0x80, 0xaa, 0x72, 0xb6, 0x2f, 0x5b, 0x9d, 0x50, 0x7a,
	0xbf, 0x8b, 0x82, 0xcd, 0x32, 0x39, 0x31, 0x34, 0x5d, 0x76, 0xf6, 0x12, 0xd2, 0xd9, 0x0f, 0xb0,
	0x00, 0x92, 0x0a, 0x05, 0x60, 0xd3, 0x4b, 0x75, 0xe8, 0x50, 0xf9, 0x16, 0x47, 0x74, 0xef, 0x13,
	0x7e, 0x01, 0x56, 0x5a, 0x7d, 0x1b, 0x2b, 0x44, 0xc5, 0xee, 0x96, 0xdc, 0xf2, 0xcb, 0x8c, 0x47,
	0x5c, 0xda, 0x65, 0x4d, 0x98, 0x79, 0x74, 0xc5, 0x1f, 0x4f, 0xed, 0xed, 0xfb, 0x45, 0xb0, 0x3e,
	0x7f, 0x6f, 0xb0, 0x02, 0xa0, 0x66, 0x59, 0x3d, 0x2c, 0xb5, 0x74, 0xa2, 0x3c, 0x96, 0x3a, 0x58,
	0x6b, 0x77, 0x6c, 0xba, 0xbd, 0x78, 0x58, 0x77, 0x5b, 0x3b, 0xc1, 0x12, 0x05, 0xaa, 0x3c, 0x62,
	0xe8, 0x47, 0xc9, 0x21, 0xec, 0x53, 0x7c, 0xb8, 0x88, 0x63, 0xff, 0x4f, 0x11, 0xc7, 0xdf, 0x7f,
	0x11, 0x2f, 0xbc, 0x87, 0x22, 0x3e, 0xf5, 0x8a, 0xc8, 0x5f, 0x63, 0x91, 0xae, 0xb1, 0xf3, 0x8e,
	0x30, 0x2e, 0x2a, 0x97, 0x52, 0x76, 0x3c, 0xe2, 0xd8, 0xd9, 0xa0, 0xce, 0x97, 0x4d, 0xd1, 0xf2,
	0xbd, 0xe0, 0xf0, 0x24, 0xfe, 0xeb, 0xe1, 0x59, 0xfa, 0xf7, 0x87, 0x27, 0xf9, 0xcf, 0x0e, 0xcf,
	0x53, 0xb0, 0xfc, 0x50, 0xd6, 0x35, 0x55, 0xb6, 0x89, 0x09, 0x77, 0x41, 0xc2, 0xe8, 0xb5, 0x1e,
	0xe3, 0x3e, 0x2d, 0xc3, 0xd4, 0x76, 0x3a, 0xef, 0x36, 0xc3, 0xbc, 0xdf, 0x0c, 0xf3, 0xc5, 0x6e,
	0xbf, 0x94, 0x79, 0xf9, 0xe2, 0x5e, 0xda, 0xeb, 0x99, 0x8a, 0xd9, 0x37, 0x6c, 0x92, 0xaf, 0xf7,
	0x5a, 0x07, 0xb8, 0x8f, 0x3c, 0x36, 0xbc, 0xe9, 0xd6, 0x93, 0x1b, 0x0b, 0x2d, 0x4b, 0x14, 0x4c,
	0x84, 0x16, 0x3f, 0x00, 0x4b, 0x87, 0x5a, 0xcb, 0x94, 0xcd, 0x3e, 0xcc, 0x4c, 0x75, 0xd3, 0xa0,
	0x73, 0xde, 0x04, 0xcb, 0x46, 0xaf, 0xa5, 0x6b, 0x56, 0x27, 0x70, 0x76, 0x3e, 0x11, 0x72, 0x86,
	0x01, 0x13, 0xca, 0x65, 0x9d, 0xbe, 0x19, 0xf6, 0x40, 0x2a, 0x94, 0xc1, 0x0b, 0xa3, 0x5a, 0x7b,
	0xf9, 0xe2, 0x5e, 0x2a, 0xe4, 0x00, 0x85, 0x99, 0xa1, 0x65, 0x7e, 0x8b, 0x81, 0xeb, 0xe7, 0xea,
	0x1f, 0x19, 0xaa, 0xbb, 0x96, 0x41, 0x2c, 0x59, 0x77, 0x9a, 0xbc, 0xad, 0xd9, 0x3a, 0xf6, 0x2e,
	0x99, 0x50, 0x93, 0xa7, 0xd3, 0x3c, 0x72, 0xcd, 0x13, 0x4d, 0x3e, 0x76, 0x99, 0x26, 0x7f, 0xfe,
	0x7a, 0x88, 0x5f, 0xfc, 0x7a, 0xd8, 0x0e, 0x0b, 0xbf, 0x70, 0x41, 0x11, 0x05, 0xb0, 0xe9, 0x07,
	0xc4, 0xe2, 0xa5, 0x1f, 0x10, 0xf0, 0x00, 0xac, 0xc8, 0xaa, 0x2a, 0x11, 0x53, 0x32, 0xf1, 0x09,
	0x39, 0xc5, 0xb4, 0xee, 0x93, 0xa5, 0x8f, 0x83, 0x5b, 0x72, 0xc2, 0xec, 0x5c, 0x40, 0xa9, 0xa2,
	0xaa, 0x8a, 0x26, 0xa2, 0x63, 0x94, 0x92, 0x83, 0x41, 0x48, 0xe1, 0x4f, 0x41, 0xe2, 0xe0, 0x61,
	0x5d, 0xd6, 0x4c, 0xc8, 0x80, 0xb8, 0x5f, 0x8c, 0xcb, 0xc8, 0xf9, 0x84, 0x69, 0xb0, 0x78, 0x2a,
	0xeb, 0x3d, 0xec, 0x15, 0x82, 0x3b, 0xb8, 0xfb, 0x3a, 0x0e, 0xd6, 0xa6, 0x6e, 0x26, 0xb8, 0x05,
	0xae, 0x95, 0x05, 0xd4, 0x94, 0x9a, 0x8f, 0xea, 0x82, 0x74, 0x54, 0x6b, 0xd4, 0x85, 0x72, 0x75,
	0xb7, 0x2a, 0x54, 0x98, 0x08, 0xbb, 0x3e, 0x18, 0xe6, 0xe0, 0x14, 0xbe, 0xa6, 0xe9, 0xf0, 0xf3,
	0x30, 0xa5, 0x2c, 0x7e, 0x55, 0xaf, 0x1e, 0x16, 0x9b, 0x55, 0xb1, 0xc6, 0x44, 0xd9, 0xec, 0x60,
	0x98, 0x63, 0xa7, 0x28, 0xa1, 0x4b, 0x04, 0xee, 0x00, 0x18, 0x50, 0x8b, 0x47, 0x95, 0x6a, 0xb3,
	0x5a, 0xdb, 0x63, 0x62, 0xec, 0x8d, 0xc1, 0x30, 0x77, 0x7d, 0x8a, 0x57, 0xec, 0xa9, 0x9a, 0xad,
	0x75, 0xdb, 0xf0, 0x1e, 0x58, 0x0b, 0x48, 0x75, 0x24, 0x8a, 0xbb, 0x4c, 0x9c, 0xcd, 0x0c, 0x86,
	0xb9, 0xf4, 0x14, 0xa3, 0x6e, 0x12, 0x72, 0x0c, 0xbf, 0x04, 0x1b, 0x01, 0x5c, 0x44, 0xc5, 0xf2,
	0xa1, 0x20, 0x89, 0x75, 0x01, 0x15, 0x9b, 0x22, 0x62, 0x16, 0xd8, 0x5b, 0x83, 0x61, 0x6e, 0x73,
	0x8a, 0x28, 0x9a, 0xb2, 0xa2, 0x63, 0xd1, 0xc0, 0x26, 0x3d, 0xdf, 0x7b, 0x60, 0x33, 0xf0, 0xd0,
	0xd8, 0xaf, 0x0a, 0x87, 0x15, 0xa9, 0x2e, 0x8a, 0x87, 0x52, 0x19, 0x09, 0xd4, 0xcb, 0x22, 0x7b,
	0x7b, 0x30, 0xcc, 0xe5, 0xa6, 0xbc, 0x34, 0x3a, 0x1a, 0xd6, 0xd5, 0x3a, 0x21, 0x7a, 0xd9, 0xc4,
	0xd4, 0xd1, 0x44, 0xb8, 0xd5, 0x8a, 0x50, 0x6b, 0x56, 0x9b, 0x8f, 0x98, 0xc4, 0xdc, 0x70, 0xab,
	0x2a, 0xee, 0xda, 0x9a, 0xdd, 0x87, 0x5b, 0xe0, 0x6a, 0x40, 0xda, 0x13, 0x6a, 0x02, 0x2a, 0x1e,
	0x32, 0x4b, 0x2c, 0x3b, 0x18, 0xe6, 0xd6, 0xa7, 0x38, 0xde, 0x6b, 0x8d, 0x5d, 0x78, 0xf6, 0x43,
	0x36, 0x72, 0xf7, 0xcf, 0x18, 0x80, 0xb3, 0x4f, 0x4b, 0xf8, 0x00, 0xdc, 0x44, 0xc2, 0xd7, 0x52,
	0x59, 0xac, 0x35, 0x85, 0xda, 0xdc, 0x44, 0x6f, 0x0c, 0x86, 0xb9, 0x6b, 0xb3, 0x4c, 0x27, 0xd7,
	0x07, 0xe0, 0xd6, 0x0c, 0xb9, 0x21, 0x1e, 0xa1, 0xb2, 0x93, 0xf9, 0x8a, 0x20, 0xed, 0x17, 0x1b,
	0xfb, 0x4c, 0xd4, 0x95, 0x63, 0xd6, 0x43, 0x83, 0xf4, 0x4c, 0x05, 0x97, 0xbd, 0x7e, 0x0f, 0x1f,
	0x80, 0xcc, 0x8c, 0xb3, 0x62, 0xa5, 0x82, 0x84, 0x46, 0x83, 0x89, 0xb1, 0x9b, 0x83, 0x61, 0x6e,
	0x63, 0xd6, 0x47, 0xd1, 0xbb, 0xdf, 0x76, 0x41, 0x76, 0x86, 0x5c, 0x7a, 0xd4, 0x14, 0x82, 0x6d,
	0xc4, 0x59, 0x7e, 0x30, 0xcc, 0x65, 0xe7, 0xbc, 0xae, 0x43, 0x8f, 0x8e, 0xb9, 0x9b, 0xf0, 0x55,
	0x5e, 0x78, 0xd7, 0x26, 0x7c, 0xa1, 0x93, 0x8e, 0xd0, 0x3f, 0xfd, 0x98, 0x8d, 0x94, 0xaa, 0x3f,
	0xbf, 0xc9, 0x46, 0x5f, 0xbd, 0xc9, 0x46, 0x7f, 0x7f, 0x93, 0x8d, 0x7e, 0xfb, 0x36, 0x1b, 0x79,
	0xf5, 0x36, 0x1b, 0xf9, 0xf5, 0x6d, 0x36, 0xf2, 0x4d, 0xa1, 0xad, 0xd9, 0x9d, 0x5e, 0x2b, 0xaf,
	0x90, 0x13, 0xfa, 0x5f, 0xa6, 0x3d, 0x3e, 0x26, 0xbd, 0xae, 0x4a, 0x0f, 0x40, 0xc1, 0xfb, 0x7b,
	0x3b, 0x73, 0xff, 0xdf, 0x9c, 0xfe, 0x6f, 0xb5, 0x12, 0xf4, 0x82, 0xdd, 0xf9, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x04, 0xef, 0x6b, 0x26, 0xdb, 0x0d, 0x00, 0x00,
}

func (m *Certifier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Certifier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Certifier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Alias) > 0 {
		i -= len(m.Alias)
		copy(dAtA[i:], m.Alias)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Alias)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestContent) > 0 {
		i -= len(m.RequestContent)
		copy(dAtA[i:], m.RequestContent)
		i = encodeVarintCert(dAtA, i, uint64(len(m.RequestContent)))
		i--
		dAtA[i] = 0x12
	}
	if m.RequestContentType != 0 {
		i = encodeVarintCert(dAtA, i, uint64(m.RequestContentType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GeneralCertificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GeneralCertificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GeneralCertificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CertTxHash) > 0 {
		i -= len(m.CertTxHash)
		copy(dAtA[i:], m.CertTxHash)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertTxHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CertCertifier) > 0 {
		i -= len(m.CertCertifier)
		copy(dAtA[i:], m.CertCertifier)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertCertifier)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CertDescription) > 0 {
		i -= len(m.CertDescription)
		copy(dAtA[i:], m.CertDescription)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertDescription)))
		i--
		dAtA[i] = 0x22
	}
	if m.ReqContent != nil {
		{
			size, err := m.ReqContent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCert(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.CertType != 0 {
		i = encodeVarintCert(dAtA, i, uint64(m.CertType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CertId) > 0 {
		i -= len(m.CertId)
		copy(dAtA[i:], m.CertId)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CompilationCertificateContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompilationCertificateContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompilationCertificateContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BytecodeHash) > 0 {
		i -= len(m.BytecodeHash)
		copy(dAtA[i:], m.BytecodeHash)
		i = encodeVarintCert(dAtA, i, uint64(len(m.BytecodeHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Compiler) > 0 {
		i -= len(m.Compiler)
		copy(dAtA[i:], m.Compiler)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Compiler)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CompilationCertificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompilationCertificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompilationCertificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CertTxHash) > 0 {
		i -= len(m.CertTxHash)
		copy(dAtA[i:], m.CertTxHash)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertTxHash)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.CertCertifier) > 0 {
		i -= len(m.CertCertifier)
		copy(dAtA[i:], m.CertCertifier)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertCertifier)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CertDescription) > 0 {
		i -= len(m.CertDescription)
		copy(dAtA[i:], m.CertDescription)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertDescription)))
		i--
		dAtA[i] = 0x32
	}
	if m.CertContent != nil {
		{
			size, err := m.CertContent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCert(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.ReqContent != nil {
		{
			size, err := m.ReqContent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCert(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.CertType != 0 {
		i = encodeVarintCert(dAtA, i, uint64(m.CertType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CertId) > 0 {
		i -= len(m.CertId)
		copy(dAtA[i:], m.CertId)
		i = encodeVarintCert(dAtA, i, uint64(len(m.CertId)))
		i--
		dAtA[i] = 0x12
	}
	if m.IssueBlockHeight != 0 {
		i = encodeVarintCert(dAtA, i, uint64(m.IssueBlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Certifier) > 0 {
		i -= len(m.Certifier)
		copy(dAtA[i:], m.Certifier)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Certifier)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pubkey != nil {
		{
			size, err := m.Pubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCert(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Library) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Library) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Library) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Publisher) > 0 {
		i -= len(m.Publisher)
		copy(dAtA[i:], m.Publisher)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Publisher)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CertificateProto) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertificateProto) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CertificateProto) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Certificate != nil {
		{
			size, err := m.Certificate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCert(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CertifierUpdateProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertifierUpdateProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CertifierUpdateProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AddOrRemove {
		i--
		if m.AddOrRemove {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Certifier) > 0 {
		i -= len(m.Certifier)
		copy(dAtA[i:], m.Certifier)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Certifier)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Alias) > 0 {
		i -= len(m.Alias)
		copy(dAtA[i:], m.Alias)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Alias)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KVPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintCert(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCert(dAtA []byte, offset int, v uint64) int {
	offset -= sovCert(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Certifier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Alias)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *RequestContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestContentType != 0 {
		n += 1 + sovCert(uint64(m.RequestContentType))
	}
	l = len(m.RequestContent)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *GeneralCertificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CertId)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	if m.CertType != 0 {
		n += 1 + sovCert(uint64(m.CertType))
	}
	if m.ReqContent != nil {
		l = m.ReqContent.Size()
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.CertDescription)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.CertCertifier)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.CertTxHash)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *CompilationCertificateContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Compiler)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.BytecodeHash)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *CompilationCertificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IssueBlockHeight != 0 {
		n += 1 + sovCert(uint64(m.IssueBlockHeight))
	}
	l = len(m.CertId)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	if m.CertType != 0 {
		n += 1 + sovCert(uint64(m.CertType))
	}
	if m.ReqContent != nil {
		l = m.ReqContent.Size()
		n += 1 + l + sovCert(uint64(l))
	}
	if m.CertContent != nil {
		l = m.CertContent.Size()
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.CertDescription)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.CertCertifier)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.CertTxHash)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pubkey != nil {
		l = m.Pubkey.Size()
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Certifier)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *Library) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Publisher)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *CertificateProto) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Certificate != nil {
		l = m.Certificate.Size()
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func (m *CertifierUpdateProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Alias)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Certifier)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	if m.AddOrRemove {
		n += 2
	}
	return n
}

func (m *KVPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovCert(uint64(l))
	}
	return n
}

func sovCert(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCert(x uint64) (n int) {
	return sovCert(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Certifier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Certifier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Certifier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alias = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestContentType", wireType)
			}
			m.RequestContentType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestContentType |= RequestContentType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestContent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestContent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GeneralCertificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GeneralCertificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GeneralCertificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertId = CertificateID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertType", wireType)
			}
			m.CertType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertType |= CertificateType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReqContent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReqContent == nil {
				m.ReqContent = &RequestContent{}
			}
			if err := m.ReqContent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertCertifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertCertifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompilationCertificateContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompilationCertificateContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompilationCertificateContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Compiler", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Compiler = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BytecodeHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BytecodeHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompilationCertificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompilationCertificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompilationCertificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueBlockHeight", wireType)
			}
			m.IssueBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssueBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertId = CertificateID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertType", wireType)
			}
			m.CertType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertType |= CertificateType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReqContent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReqContent == nil {
				m.ReqContent = &RequestContent{}
			}
			if err := m.ReqContent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertContent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CertContent == nil {
				m.CertContent = &CompilationCertificateContent{}
			}
			if err := m.CertContent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertCertifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertCertifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pubkey == nil {
				m.Pubkey = &types.Any{}
			}
			if err := m.Pubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Library) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Library: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Library: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Publisher", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Publisher = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CertificateProto) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertificateProto: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertificateProto: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Certificate == nil {
				m.Certificate = &types.Any{}
			}
			if err := m.Certificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CertifierUpdateProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertifierUpdateProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertifierUpdateProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alias = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddOrRemove", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AddOrRemove = AddOrRemove(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCert
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCert
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCert
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCert
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCert(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCert
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCert(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCert
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCert
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCert
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCert
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCert
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCert
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCert        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCert          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCert = fmt.Errorf("proto: unexpected end of group")
)
