// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shentu/shield/v1alpha1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the shield genesis state.
type GenesisState struct {
	ShieldAdmin         string                                      `protobuf:"bytes,1,opt,name=shield_admin,json=shieldAdmin,proto3" json:"shield_admin,omitempty" yaml:"shield_admin"`
	NextPoolId          uint64                                      `protobuf:"varint,2,opt,name=next_pool_id,json=nextPoolId,proto3" json:"next_pool_id,omitempty" yaml:"next_pool_id"`
	NextPurchaseId      uint64                                      `protobuf:"varint,3,opt,name=next_purchase_id,json=nextPurchaseId,proto3" json:"next_purchase_id,omitempty" yaml:"next_purchase_id"`
	PoolParams          PoolParams                                  `protobuf:"bytes,4,opt,name=pool_params,json=poolParams,proto3" json:"pool_params" yaml:"pool_params"`
	ClaimProposalParams ClaimProposalParams                         `protobuf:"bytes,5,opt,name=claim_proposal_params,json=claimProposalParams,proto3" json:"claim_proposal_params" yaml:"claim_proposal_params"`
	TotalCollateral     github_com_cosmos_cosmos_sdk_types.Int      `protobuf:"bytes,6,opt,name=total_collateral,json=totalCollateral,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_collateral" yaml:"total_collateral"`
	TotalWithdrawing    github_com_cosmos_cosmos_sdk_types.Int      `protobuf:"bytes,7,opt,name=total_withdrawing,json=totalWithdrawing,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_withdrawing" yaml:"total_withdrawing"`
	TotalShield         github_com_cosmos_cosmos_sdk_types.Int      `protobuf:"bytes,8,opt,name=total_shield,json=totalShield,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_shield" yaml:"total_shield"`
	TotalClaimed        github_com_cosmos_cosmos_sdk_types.Int      `protobuf:"bytes,9,opt,name=total_claimed,json=totalClaimed,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_claimed" yaml:"total_claimed"`
	Fees                github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,10,rep,name=fees,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"fees" yaml:"fees"`
	Pools               []Pool                                      `protobuf:"bytes,11,rep,name=pools,proto3" json:"pools" yaml:"pools"`
	Providers           []Provider                                  `protobuf:"bytes,12,rep,name=providers,proto3" json:"providers" yaml:"providers"`
	Withdraws           []Withdraw                                  `protobuf:"bytes,13,rep,name=withdraws,proto3" json:"withdraws" yaml:"withdraws"`
	GlobalStakingPool   github_com_cosmos_cosmos_sdk_types.Int      `protobuf:"bytes,14,opt,name=global_staking_pool,json=globalStakingPool,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"global_staking_pool" yaml:"global_staking_pool"`
	Purchases           []Purchase                                  `protobuf:"bytes,15,rep,name=purchases,proto3" json:"purchases" yaml:"purchases"`
	DonationPool        DonationPool                                `protobuf:"bytes,16,opt,name=donation_pool,json=donationPool,proto3" json:"donation_pool" yaml:"donation_pool"`
	PendingPayouts      []PendingPayout                             `protobuf:"bytes,17,rep,name=pending_payouts,json=pendingPayouts,proto3" json:"pending_payouts" yaml:"pending_payouts"`
	BlockRewardParams   BlockRewardParams                           `protobuf:"bytes,18,opt,name=block_reward_params,json=blockRewardParams,proto3" json:"block_reward_params" yaml:"block_reward_params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c089c09a119aaa04, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

// PoolParams defines the parameters for the shield pool.
type PoolParams struct {
	ProtectionPeriod  time.Duration                            `protobuf:"bytes,1,opt,name=protection_period,json=protectionPeriod,proto3,stdduration" json:"protection_period" yaml:"protection_period"`
	ShieldFeesRate    github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,2,opt,name=shield_fees_rate,json=shieldFeesRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"shield_fees_rate" yaml:"shield_fees_rate"`
	WithdrawPeriod    time.Duration                            `protobuf:"bytes,3,opt,name=withdraw_period,json=withdrawPeriod,proto3,stdduration" json:"withdraw_period" yaml:"withdraw_period"`
	PoolShieldLimit   github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,4,opt,name=pool_shield_limit,json=poolShieldLimit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"pool_shield_limit" yaml:"pool_shield_limit"`
	MinShieldPurchase github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=min_shield_purchase,json=minShieldPurchase,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"min_shield_purchase"`
	CooldownPeriod    time.Duration                            `protobuf:"bytes,6,opt,name=cooldown_period,json=cooldownPeriod,proto3,stdduration" json:"cooldown_period" yaml:"cooldown_period"`
}

func (m *PoolParams) Reset()         { *m = PoolParams{} }
func (m *PoolParams) String() string { return proto.CompactTextString(m) }
func (*PoolParams) ProtoMessage()    {}
func (*PoolParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c089c09a119aaa04, []int{1}
}
func (m *PoolParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolParams.Merge(m, src)
}
func (m *PoolParams) XXX_Size() int {
	return m.Size()
}
func (m *PoolParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolParams.DiscardUnknown(m)
}

var xxx_messageInfo_PoolParams proto.InternalMessageInfo

// ClaimProposalParams defines the parameters for the shield claim proposals.
type ClaimProposalParams struct {
	ClaimPeriod  time.Duration                            `protobuf:"bytes,1,opt,name=claim_period,json=claimPeriod,proto3,stdduration" json:"claim_period" yaml:"claim_period"`
	PayoutPeriod time.Duration                            `protobuf:"bytes,2,opt,name=payout_period,json=payoutPeriod,proto3,stdduration" json:"payout_period" yaml:"payout_period"`
	MinDeposit   github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=min_deposit,json=minDeposit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"min_deposit"`
	DepositRate  github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,4,opt,name=deposit_rate,json=depositRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"deposit_rate" yaml:"deposit_rate"`
	FeesRate     github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,5,opt,name=fees_rate,json=feesRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"fees_rate" yaml:"fees_rate"`
}

func (m *ClaimProposalParams) Reset()         { *m = ClaimProposalParams{} }
func (m *ClaimProposalParams) String() string { return proto.CompactTextString(m) }
func (*ClaimProposalParams) ProtoMessage()    {}
func (*ClaimProposalParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c089c09a119aaa04, []int{2}
}
func (m *ClaimProposalParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClaimProposalParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimProposalParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClaimProposalParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimProposalParams.Merge(m, src)
}
func (m *ClaimProposalParams) XXX_Size() int {
	return m.Size()
}
func (m *ClaimProposalParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimProposalParams.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimProposalParams proto.InternalMessageInfo

// BlockRewardParams defines the parameters for shield block reward.
type BlockRewardParams struct {
	ModelParamA    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=model_param_a,json=modelParamA,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"model_param_a" yaml:"model_param_a"`
	ModelParamB    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=model_param_b,json=modelParamB,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"model_param_b" yaml:"model_param_b"`
	TargetLeverage github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=target_leverage,json=targetLeverage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"target_leverage" yaml:"target_leverage"`
}

func (m *BlockRewardParams) Reset()         { *m = BlockRewardParams{} }
func (m *BlockRewardParams) String() string { return proto.CompactTextString(m) }
func (*BlockRewardParams) ProtoMessage()    {}
func (*BlockRewardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c089c09a119aaa04, []int{3}
}
func (m *BlockRewardParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRewardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockRewardParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockRewardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRewardParams.Merge(m, src)
}
func (m *BlockRewardParams) XXX_Size() int {
	return m.Size()
}
func (m *BlockRewardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRewardParams.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRewardParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "shentu.shield.v1alpha1.GenesisState")
	proto.RegisterType((*PoolParams)(nil), "shentu.shield.v1alpha1.PoolParams")
	proto.RegisterType((*ClaimProposalParams)(nil), "shentu.shield.v1alpha1.ClaimProposalParams")
	proto.RegisterType((*BlockRewardParams)(nil), "shentu.shield.v1alpha1.BlockRewardParams")
}

func init() {
	proto.RegisterFile("shentu/shield/v1alpha1/genesis.proto", fileDescriptor_c089c09a119aaa04)
}

var fileDescriptor_c089c09a119aaa04 = []byte{
	// 1284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xbf, 0x6f, 0xdb, 0xc6,
	0x17, 0xb7, 0x62, 0x3b, 0xdf, 0xf8, 0x28, 0xcb, 0xd2, 0x29, 0xdf, 0x84, 0x71, 0x03, 0xd1, 0xb8,
	0xa6, 0x85, 0x8b, 0xa0, 0x64, 0x9d, 0x4e, 0xcd, 0x16, 0xda, 0x49, 0xe3, 0x36, 0x83, 0x71, 0x19,
	0x5a, 0x14, 0x28, 0xd4, 0x13, 0x79, 0xa6, 0x58, 0x93, 0x3c, 0x96, 0x77, 0xb2, 0x13, 0xb4, 0x1d,
	0x0b, 0x74, 0xec, 0xd8, 0x6e, 0x59, 0x9b, 0x3f, 0xa2, 0x73, 0xc6, 0x8c, 0x45, 0x07, 0xa7, 0x48,
	0x96, 0xcc, 0xf9, 0x0b, 0x8a, 0xfb, 0x41, 0x91, 0x52, 0xa4, 0xc4, 0x02, 0x32, 0xd9, 0xf7, 0xf8,
	0xde, 0xe7, 0x73, 0xef, 0xf7, 0x09, 0x5c, 0xe3, 0x43, 0x9a, 0x89, 0x91, 0xc7, 0x87, 0x31, 0x4d,
	0x42, 0xef, 0x78, 0x87, 0x24, 0xf9, 0x90, 0xec, 0x78, 0x11, 0xcd, 0x28, 0x8f, 0xb9, 0x9b, 0x17,
	0x4c, 0x30, 0x78, 0x49, 0x6b, 0xb9, 0x5a, 0xcb, 0x2d, 0xb5, 0x36, 0x2f, 0x46, 0x2c, 0x62, 0x4a,
	0xc5, 0x93, 0xff, 0x69, 0xed, 0xcd, 0x5e, 0xc0, 0x78, 0xca, 0xb8, 0x37, 0x20, 0x9c, 0x7a, 0xc7,
	0x3b, 0x03, 0x2a, 0xc8, 0x8e, 0x17, 0xb0, 0x38, 0x33, 0xdf, 0x9d, 0x88, 0xb1, 0x28, 0xa1, 0x9e,
	0x3a, 0x0d, 0x46, 0x87, 0x9e, 0x88, 0x53, 0xca, 0x05, 0x49, 0xf3, 0x12, 0x60, 0x5a, 0x21, 0x1c,
	0x15, 0x44, 0xc4, 0xac, 0x04, 0x78, 0x7f, 0xce, 0xa5, 0xcd, 0xf5, 0x94, 0x12, 0xfa, 0xb3, 0x05,
	0x9a, 0x9f, 0x6b, 0x2f, 0xee, 0x0b, 0x22, 0x28, 0xbc, 0x09, 0x9a, 0x5a, 0xa1, 0x4f, 0xc2, 0x34,
	0xce, 0xec, 0xc6, 0x56, 0x63, 0x7b, 0xcd, 0xbf, 0xfc, 0xea, 0xd4, 0xe9, 0x3e, 0x24, 0x69, 0x72,
	0x13, 0xd5, 0xbf, 0x22, 0x6c, 0xe9, 0xe3, 0x2d, 0x79, 0x82, 0x9f, 0x81, 0x66, 0x46, 0x1f, 0x88,
	0x7e, 0xce, 0x58, 0xd2, 0x8f, 0x43, 0xfb, 0xdc, 0x56, 0x63, 0x7b, 0xa5, 0x6e, 0x5b, 0xff, 0x8a,
	0x30, 0x90, 0xc7, 0x03, 0xc6, 0x92, 0xfd, 0x10, 0xde, 0x06, 0x6d, 0xfd, 0x71, 0x54, 0x04, 0x43,
	0xc2, 0xa9, 0x34, 0x5f, 0x56, 0xe6, 0xef, 0xbd, 0x3a, 0x75, 0x2e, 0xd7, 0xcd, 0x2b, 0x0d, 0x84,
	0x5b, 0x0a, 0xc2, 0x48, 0xf6, 0x43, 0xd8, 0x07, 0x96, 0x82, 0xcf, 0x49, 0x41, 0x52, 0x6e, 0xaf,
	0x6c, 0x35, 0xb6, 0xad, 0x1b, 0xc8, 0x9d, 0x9d, 0x18, 0x57, 0x72, 0x1f, 0x28, 0x4d, 0x7f, 0xf3,
	0xc9, 0xa9, 0xb3, 0xf4, 0xea, 0xd4, 0x81, 0x9a, 0xa9, 0x06, 0x82, 0x30, 0xc8, 0xc7, 0x7a, 0xf0,
	0x97, 0x06, 0xf8, 0x7f, 0x90, 0x90, 0x38, 0xed, 0xe7, 0x05, 0xcb, 0x19, 0x27, 0x63, 0xae, 0x55,
	0xc5, 0x75, 0x7d, 0x1e, 0xd7, 0xae, 0x34, 0x3a, 0x30, 0x36, 0x86, 0xf4, 0x9a, 0x21, 0xbd, 0xaa,
	0x49, 0x67, 0xe2, 0x22, 0xdc, 0x0d, 0x5e, 0x37, 0x85, 0x02, 0xb4, 0x05, 0x13, 0x24, 0xe9, 0x07,
	0x2c, 0x49, 0x88, 0xa0, 0x05, 0x49, 0xec, 0xf3, 0x2a, 0x55, 0xfb, 0x12, 0xf4, 0x9f, 0x53, 0xe7,
	0xc3, 0x28, 0x16, 0xc3, 0xd1, 0xc0, 0x0d, 0x58, 0xea, 0x99, 0x52, 0xd3, 0x7f, 0x3e, 0xe6, 0xe1,
	0x91, 0x27, 0x1e, 0xe6, 0x94, 0xbb, 0xfb, 0x99, 0xa8, 0xa2, 0x3b, 0x8d, 0x87, 0xf0, 0x86, 0x12,
	0xed, 0x8e, 0x25, 0xf0, 0x04, 0x74, 0xb4, 0xd6, 0x49, 0x2c, 0x86, 0x61, 0x41, 0x4e, 0xe2, 0x2c,
	0xb2, 0xff, 0xa7, 0x68, 0xbf, 0x58, 0x98, 0xd6, 0xae, 0xd3, 0xd6, 0x00, 0x11, 0xd6, 0xae, 0x7d,
	0x55, 0x89, 0xe0, 0x10, 0x34, 0xb5, 0x9e, 0x0e, 0xab, 0x7d, 0x41, 0x71, 0xde, 0x5e, 0x98, 0xb3,
	0x5b, 0xe7, 0xd4, 0x58, 0x08, 0x5b, 0xea, 0x78, 0x5f, 0x9d, 0xe0, 0x11, 0x58, 0x37, 0x81, 0x90,
	0x51, 0xa7, 0xa1, 0xbd, 0xa6, 0xa8, 0xee, 0x2c, 0x4c, 0x75, 0x71, 0x22, 0xaa, 0x1a, 0x0c, 0x61,
	0xed, 0xc6, 0xae, 0x3e, 0x42, 0x01, 0x56, 0x0e, 0x29, 0xe5, 0x36, 0xd8, 0x5a, 0xde, 0xb6, 0x6e,
	0x5c, 0x75, 0x35, 0x94, 0x2b, 0x47, 0x82, 0x6b, 0x46, 0x82, 0xbb, 0x47, 0x83, 0x5d, 0x16, 0x67,
	0xbe, 0x6f, 0x8a, 0xc5, 0xd2, 0xb8, 0xd2, 0x0e, 0x3d, 0x7e, 0xe6, 0x5c, 0x3f, 0xc3, 0x85, 0x0c,
	0x04, 0xc7, 0x8a, 0x0d, 0xde, 0x05, 0xab, 0xb2, 0xa2, 0xb9, 0x6d, 0x19, 0xda, 0x37, 0xb4, 0x87,
	0x7f, 0xd1, 0xd0, 0x36, 0xab, 0xc6, 0xe0, 0x08, 0x6b, 0x00, 0xf8, 0x35, 0x58, 0xcb, 0x0b, 0x76,
	0x1c, 0x87, 0xb4, 0xe0, 0x76, 0x53, 0xa1, 0x6d, 0xcd, 0x45, 0x33, 0x8a, 0xbe, 0x6d, 0x10, 0xdb,
	0x06, 0xb1, 0x04, 0x40, 0xb8, 0x02, 0x93, 0xc8, 0x65, 0x49, 0x70, 0x7b, 0xfd, 0xcd, 0xc8, 0x65,
	0xa1, 0x4c, 0x23, 0x8f, 0x01, 0x10, 0xae, 0xc0, 0xe0, 0x4f, 0xa0, 0x1b, 0x25, 0x6c, 0x20, 0xf3,
	0x2f, 0xc8, 0x51, 0x9c, 0x45, 0x6a, 0x20, 0xd9, 0x2d, 0x95, 0xe6, 0x7b, 0x0b, 0xa7, 0x79, 0x53,
	0x73, 0xcd, 0x80, 0x44, 0xb8, 0xa3, 0xa5, 0xf7, 0xb5, 0x50, 0x86, 0x53, 0x45, 0xcc, 0x8c, 0x2b,
	0x6e, 0x6f, 0xbc, 0x25, 0x62, 0x46, 0xf1, 0xb5, 0x88, 0x95, 0x00, 0x32, 0x62, 0xe5, 0xff, 0x30,
	0x02, 0xeb, 0x21, 0xcb, 0xd4, 0x02, 0xd0, 0x1e, 0xb5, 0xd5, 0x40, 0xba, 0x36, 0x0f, 0x7d, 0xcf,
	0x28, 0xab, 0x2c, 0x5f, 0x35, 0x0c, 0xa6, 0x68, 0x27, 0x80, 0x10, 0x6e, 0x86, 0x35, 0x5d, 0x98,
	0x81, 0x8d, 0x9c, 0x66, 0xa1, 0x72, 0x93, 0x3c, 0x64, 0x23, 0xc1, 0xed, 0x8e, 0x72, 0xe4, 0x83,
	0xb9, 0x8e, 0x68, 0xf5, 0x03, 0xa5, 0xed, 0xf7, 0x0c, 0xd7, 0x25, 0xe3, 0xcd, 0x24, 0x16, 0xc2,
	0xad, 0xbc, 0xae, 0xce, 0xe1, 0xcf, 0xa0, 0x3b, 0x48, 0x58, 0x70, 0xd4, 0x2f, 0xe8, 0x09, 0x29,
	0xc2, 0x72, 0xde, 0x42, 0xe5, 0xde, 0x47, 0xf3, 0x38, 0x7d, 0x69, 0x82, 0x95, 0x85, 0x99, 0xb6,
	0xc8, 0xf0, 0x9a, 0x8c, 0xcd, 0xc0, 0x44, 0xb8, 0x33, 0x98, 0x36, 0xbb, 0x79, 0xe1, 0xd7, 0x47,
	0xce, 0xd2, 0xcb, 0x47, 0xce, 0x12, 0xfa, 0x6b, 0x15, 0x80, 0x6a, 0x65, 0xc0, 0x04, 0x74, 0xe4,
	0x0e, 0xa5, 0x81, 0x8e, 0x14, 0x2d, 0x62, 0x16, 0xaa, 0x75, 0x69, 0xdd, 0xb8, 0xe2, 0xea, 0xdd,
	0xec, 0x96, 0xbb, 0xd9, 0xdd, 0x33, 0xbb, 0x79, 0x3c, 0xf3, 0xed, 0x71, 0xf5, 0x4f, 0x22, 0xa0,
	0xdf, 0x9f, 0x39, 0x0d, 0xdc, 0xae, 0xe4, 0x07, 0x4a, 0x0c, 0x39, 0x68, 0x9b, 0xcd, 0x2b, 0x7b,
	0xb8, 0x5f, 0x10, 0x41, 0xd5, 0x7e, 0x5d, 0x6c, 0xe0, 0xef, 0xd1, 0xa0, 0x1a, 0xf8, 0xd3, 0x78,
	0x08, 0xb7, 0xb4, 0xe8, 0x0e, 0xa5, 0x1c, 0xcb, 0xc7, 0xc0, 0x21, 0xd8, 0x28, 0x1b, 0xa7, 0x74,
	0x70, 0xf9, 0x6d, 0x0e, 0xa2, 0xc9, 0xf4, 0x4e, 0xd9, 0x6b, 0xf7, 0x5a, 0xa5, 0xd4, 0x38, 0x77,
	0x0c, 0x3a, 0x6a, 0xe3, 0x9a, 0x1b, 0x25, 0x71, 0x1a, 0x0b, 0xb5, 0xbc, 0x17, 0xdb, 0x2b, 0xda,
	0x3b, 0xbb, 0xb6, 0xc2, 0xeb, 0x80, 0x08, 0x6f, 0x48, 0x99, 0x9e, 0xf3, 0xf7, 0xa4, 0x04, 0xfe,
	0x08, 0xba, 0x69, 0x9c, 0x95, 0x5a, 0x65, 0x2f, 0xd9, 0xab, 0xaa, 0x9c, 0xaf, 0xcc, 0x1c, 0xc7,
	0x6a, 0x16, 0x7f, 0x22, 0x2f, 0xf5, 0xf8, 0x99, 0xb3, 0x7d, 0x86, 0x4b, 0xe9, 0xc9, 0xdb, 0x49,
	0xe3, 0x4c, 0x33, 0x97, 0x5d, 0x2d, 0x83, 0x1b, 0x30, 0x96, 0x84, 0xec, 0x64, 0x5c, 0x3d, 0xe7,
	0x17, 0x0c, 0xee, 0x94, 0xbd, 0x09, 0x6e, 0x29, 0xd5, 0xc1, 0xad, 0x15, 0xf0, 0x1f, 0x2b, 0xa0,
	0x3b, 0xe3, 0x1d, 0x02, 0xbf, 0x05, 0x4d, 0xf3, 0xf6, 0x38, 0x63, 0x11, 0x3b, 0xe6, 0x1a, 0xdd,
	0x89, 0x87, 0x4b, 0xed, 0x0e, 0x96, 0x7e, 0xb3, 0xe8, 0xec, 0x7e, 0x07, 0xd6, 0x75, 0x73, 0x97,
	0xf8, 0xe7, 0xde, 0x86, 0xbf, 0x35, 0x39, 0x8e, 0x26, 0xac, 0x35, 0x41, 0x53, 0xcb, 0x0c, 0x43,
	0x02, 0x2c, 0x99, 0xc7, 0x90, 0xe6, 0x8c, 0xc7, 0xc2, 0x5e, 0x7e, 0xf7, 0xf9, 0x03, 0x69, 0x9c,
	0xed, 0x69, 0x78, 0xf9, 0x18, 0x31, 0x4c, 0xba, 0x0d, 0x57, 0x16, 0x7e, 0x8c, 0xe8, 0x42, 0x35,
	0xd1, 0xab, 0x63, 0x21, 0x6c, 0x99, 0xa3, 0xea, 0xbf, 0x3e, 0x58, 0xab, 0xba, 0x7d, 0x55, 0xd1,
	0xf8, 0x0b, 0xd3, 0xb4, 0xab, 0x07, 0x83, 0xe1, 0xb8, 0x70, 0x68, 0x1a, 0xbc, 0x56, 0x1b, 0x2f,
	0xcf, 0x81, 0xce, 0x6b, 0x33, 0x13, 0x7e, 0x0f, 0xd6, 0x53, 0x16, 0x52, 0xf3, 0x18, 0xed, 0x13,
	0xf3, 0x73, 0xe0, 0xce, 0xc2, 0x97, 0x30, 0x99, 0x9c, 0x00, 0x43, 0xd8, 0x52, 0x67, 0xc5, 0x75,
	0x6b, 0x9a, 0x6b, 0x60, 0xc6, 0xdb, 0x3b, 0xe1, 0x1a, 0x4c, 0x70, 0xf9, 0xf0, 0x07, 0xb0, 0x21,
	0x48, 0x11, 0x51, 0xd1, 0x4f, 0xe8, 0x31, 0x2d, 0x48, 0x44, 0xd5, 0x60, 0x5b, 0xf3, 0xef, 0x2e,
	0xcc, 0x66, 0x5a, 0x71, 0x0a, 0x0e, 0xe1, 0x96, 0x96, 0xdc, 0x33, 0x82, 0x2a, 0xd4, 0xfe, 0x97,
	0x4f, 0x9e, 0xf7, 0x1a, 0x4f, 0x9f, 0xf7, 0x1a, 0xff, 0x3e, 0xef, 0x35, 0x7e, 0x7b, 0xd1, 0x5b,
	0x7a, 0xfa, 0xa2, 0xb7, 0xf4, 0xf7, 0x8b, 0xde, 0xd2, 0x37, 0x3b, 0x75, 0x56, 0x5a, 0x88, 0xf8,
	0xe8, 0x90, 0x8d, 0xb2, 0x50, 0x35, 0x85, 0x67, 0x7e, 0xce, 0x3d, 0x28, 0x7f, 0xd0, 0xa9, 0x4b,
	0x0c, 0xce, 0xab, 0xee, 0xf9, 0xf4, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x12, 0xfa, 0x02,
	0xa3, 0x0e, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BlockRewardParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x92
	if len(m.PendingPayouts) > 0 {
		for iNdEx := len(m.PendingPayouts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingPayouts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	{
		size, err := m.DonationPool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	if len(m.Purchases) > 0 {
		for iNdEx := len(m.Purchases) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Purchases[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	{
		size := m.GlobalStakingPool.Size()
		i -= size
		if _, err := m.GlobalStakingPool.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	if len(m.Withdraws) > 0 {
		for iNdEx := len(m.Withdraws) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Withdraws[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Providers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.Fees) > 0 {
		for iNdEx := len(m.Fees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	{
		size := m.TotalClaimed.Size()
		i -= size
		if _, err := m.TotalClaimed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.TotalShield.Size()
		i -= size
		if _, err := m.TotalShield.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.TotalWithdrawing.Size()
		i -= size
		if _, err := m.TotalWithdrawing.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.TotalCollateral.Size()
		i -= size
		if _, err := m.TotalCollateral.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.ClaimProposalParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.PoolParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.NextPurchaseId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPurchaseId))
		i--
		dAtA[i] = 0x18
	}
	if m.NextPoolId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ShieldAdmin) > 0 {
		i -= len(m.ShieldAdmin)
		copy(dAtA[i:], m.ShieldAdmin)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ShieldAdmin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n5, err5 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.CooldownPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.CooldownPeriod):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintGenesis(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x32
	if len(m.MinShieldPurchase) > 0 {
		for iNdEx := len(m.MinShieldPurchase) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinShieldPurchase[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size := m.PoolShieldLimit.Size()
		i -= size
		if _, err := m.PoolShieldLimit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	n6, err6 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.WithdrawPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.WithdrawPeriod):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintGenesis(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x1a
	{
		size := m.ShieldFeesRate.Size()
		i -= size
		if _, err := m.ShieldFeesRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n7, err7 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ProtectionPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ProtectionPeriod):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintGenesis(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClaimProposalParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimProposalParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimProposalParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FeesRate.Size()
		i -= size
		if _, err := m.FeesRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.DepositRate.Size()
		i -= size
		if _, err := m.DepositRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.MinDeposit) > 0 {
		for iNdEx := len(m.MinDeposit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinDeposit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	n8, err8 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.PayoutPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.PayoutPeriod):])
	if err8 != nil {
		return 0, err8
	}
	i -= n8
	i = encodeVarintGenesis(dAtA, i, uint64(n8))
	i--
	dAtA[i] = 0x12
	n9, err9 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ClaimPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ClaimPeriod):])
	if err9 != nil {
		return 0, err9
	}
	i -= n9
	i = encodeVarintGenesis(dAtA, i, uint64(n9))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *BlockRewardParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRewardParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRewardParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TargetLeverage.Size()
		i -= size
		if _, err := m.TargetLeverage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.ModelParamB.Size()
		i -= size
		if _, err := m.ModelParamB.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.ModelParamA.Size()
		i -= size
		if _, err := m.ModelParamA.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ShieldAdmin)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.NextPoolId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPoolId))
	}
	if m.NextPurchaseId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPurchaseId))
	}
	l = m.PoolParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ClaimProposalParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalCollateral.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalWithdrawing.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalShield.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalClaimed.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Fees) > 0 {
		for _, e := range m.Fees {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Providers) > 0 {
		for _, e := range m.Providers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Withdraws) > 0 {
		for _, e := range m.Withdraws {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.GlobalStakingPool.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Purchases) > 0 {
		for _, e := range m.Purchases {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.DonationPool.Size()
	n += 2 + l + sovGenesis(uint64(l))
	if len(m.PendingPayouts) > 0 {
		for _, e := range m.PendingPayouts {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	l = m.BlockRewardParams.Size()
	n += 2 + l + sovGenesis(uint64(l))
	return n
}

func (m *PoolParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ProtectionPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ShieldFeesRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.WithdrawPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	l = m.PoolShieldLimit.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MinShieldPurchase) > 0 {
		for _, e := range m.MinShieldPurchase {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.CooldownPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *ClaimProposalParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ClaimPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.PayoutPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MinDeposit) > 0 {
		for _, e := range m.MinDeposit {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.DepositRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.FeesRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *BlockRewardParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ModelParamA.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ModelParamB.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TargetLeverage.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShieldAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShieldAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPoolId", wireType)
			}
			m.NextPoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPurchaseId", wireType)
			}
			m.NextPurchaseId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPurchaseId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimProposalParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimProposalParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCollateral", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalCollateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalWithdrawing", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalWithdrawing.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShield", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShield.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalClaimed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalClaimed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fees = append(m.Fees, types.DecCoin{})
			if err := m.Fees[len(m.Fees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, Pool{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, Provider{})
			if err := m.Providers[len(m.Providers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Withdraws", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Withdraws = append(m.Withdraws, Withdraw{})
			if err := m.Withdraws[len(m.Withdraws)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalStakingPool", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GlobalStakingPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purchases", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purchases = append(m.Purchases, Purchase{})
			if err := m.Purchases[len(m.Purchases)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DonationPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DonationPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingPayouts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingPayouts = append(m.PendingPayouts, PendingPayout{})
			if err := m.PendingPayouts[len(m.PendingPayouts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockRewardParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockRewardParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtectionPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ProtectionPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShieldFeesRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShieldFeesRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.WithdrawPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolShieldLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolShieldLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinShieldPurchase", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinShieldPurchase = append(m.MinShieldPurchase, types.Coin{})
			if err := m.MinShieldPurchase[len(m.MinShieldPurchase)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CooldownPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.CooldownPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClaimProposalParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimProposalParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimProposalParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ClaimPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayoutPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.PayoutPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDeposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinDeposit = append(m.MinDeposit, types.Coin{})
			if err := m.MinDeposit[len(m.MinDeposit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeesRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeesRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockRewardParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRewardParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRewardParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelParamA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ModelParamA.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelParamB", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ModelParamB.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetLeverage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetLeverage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
