name: Sims
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.22
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.22
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: ${{ env.GIT_DIFF != '' }}
      - name: test nondeterminism
        run: |
          make test-sim-nondeterminism
        if: ${{ env.GIT_DIFF != '' }}

  test-sim-import-export:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.22
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: ${{ env.GIT_DIFF != '' }}
      - name: test-sim-import-export
        run: |
          make test-sim-import-export
        if: ${{ env.GIT_DIFF != '' }}

  test-sim-after-import:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.22
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: ${{ env.GIT_DIFF != '' }}
      - name: test after import
        run: |
          make test-sim-after-import
        if: ${{ env.GIT_DIFF != '' }}

  test-sim-multi-seed-short:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.22
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: ${{ env.GIT_DIFF != '' }}
      - name: test-sim-multi-seed-short
        run: |
          make test-sim-multi-seed-short
        if: ${{ env.GIT_DIFF != '' }}
